server:
  port: 8080
spring:
  application:
    name: microserver-provider-user
eureka:
  client:
      service-url:
        defaultZone: http://root:1234567@localhost:8762/eureka/

  instance:
    prefer-ip-address: true

