package com.anji.allways.business.vo;

import java.util.Date;
import java.util.List;

public class WarehouseVO {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.short_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        shortName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.company_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       companyId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.space_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       spaceAmount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.occupied_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       occupiedAmount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.provinceName
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        provinceName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.provinceCode
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        provinceCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.cityName
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        cityName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.cityCode
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        cityCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.districtName
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        districtName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.districtCode
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        districtCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        address;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.longitude
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Float                         longitude;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.latitude
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Float                         latitude;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.register_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        registerPicturePath;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.contactor
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        contactor;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.contactor_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        contactorMobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.business_start_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        businessStartTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.business_end_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        businessEndTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.warning_empty_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       warningEmptyAmount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.warning_occupied_percent
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Float                         warningOccupiedPercent;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        comment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int                           status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String                        reserved;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date                          createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer                       updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_warehouse.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date                          updateTime;

    /**
     * 使用告警类型 0：未知 1：数量 2：百分比
     */
    private Integer                       warningType;

    /**
     * 营业时间（全天或“开始时间-结束时间（09:00-18:00）”）
     */
    private String                        businessTimeName;

    /**
     * 仓库状态名称
     */
    private String                        statusName;

    /**
     * 库存利用率
     */
    private String                        useRate;

    /**
     * 客户数量
     */
    private String                        customerNum;

    /**
     * 闲置车位数
     */
    private String                        freeAmount;

    /**
     * 上级仓库名称
     */
    private String                        parentName;

    /**
     * 客户信息List
     */
    private List<WarehouseLinkCustomerVO> customerList;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.id
     * @return the value of tb_warehouse.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.id
     * @param id
     *            the value for tb_warehouse.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.name
     * @return the value of tb_warehouse.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.name
     * @param name
     *            the value for tb_warehouse.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.short_name
     * @return the value of tb_warehouse.short_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.short_name
     * @param shortName
     *            the value for tb_warehouse.short_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.parent_id
     * @return the value of tb_warehouse.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.parent_id
     * @param parentId
     *            the value for tb_warehouse.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.company_id
     * @return the value of tb_warehouse.company_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.company_id
     * @param companyId
     *            the value for tb_warehouse.company_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.space_amount
     * @return the value of tb_warehouse.space_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getSpaceAmount() {
        return spaceAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.space_amount
     * @param spaceAmount
     *            the value for tb_warehouse.space_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setSpaceAmount(Integer spaceAmount) {
        this.spaceAmount = spaceAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.occupied_amount
     * @return the value of tb_warehouse.occupied_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getOccupiedAmount() {
        return occupiedAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.occupied_amount
     * @param occupiedAmount
     *            the value for tb_warehouse.occupied_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setOccupiedAmount(Integer occupiedAmount) {
        this.occupiedAmount = occupiedAmount;
    }

    /**
     * Getter method for property <tt>provinceName</tt>.
     * @return property value of provinceName
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * Setter method for property <tt>provinceName</tt>.
     * @param provinceName
     *            value to be assigned to property provinceName
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * Getter method for property <tt>provinceCode</tt>.
     * @return property value of provinceCode
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * Setter method for property <tt>provinceCode</tt>.
     * @param provinceCode
     *            value to be assigned to property provinceCode
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * Getter method for property <tt>cityName</tt>.
     * @return property value of cityName
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Setter method for property <tt>cityName</tt>.
     * @param cityName
     *            value to be assigned to property cityName
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * Getter method for property <tt>cityCode</tt>.
     * @return property value of cityCode
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * Setter method for property <tt>cityCode</tt>.
     * @param cityCode
     *            value to be assigned to property cityCode
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * Getter method for property <tt>districtName</tt>.
     * @return property value of districtName
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * Setter method for property <tt>districtName</tt>.
     * @param districtName
     *            value to be assigned to property districtName
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * Getter method for property <tt>districtCode</tt>.
     * @return property value of districtCode
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * Setter method for property <tt>districtCode</tt>.
     * @param districtCode
     *            value to be assigned to property districtCode
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.address
     * @return the value of tb_warehouse.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.address
     * @param address
     *            the value for tb_warehouse.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.longitude
     * @return the value of tb_warehouse.longitude
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.longitude
     * @param longitude
     *            the value for tb_warehouse.longitude
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.latitude
     * @return the value of tb_warehouse.latitude
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.latitude
     * @param latitude
     *            the value for tb_warehouse.latitude
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.register_picture_path
     * @return the value of tb_warehouse.register_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getRegisterPicturePath() {
        return registerPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.register_picture_path
     * @param registerPicturePath
     *            the value for tb_warehouse.register_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setRegisterPicturePath(String registerPicturePath) {
        this.registerPicturePath = registerPicturePath == null ? null : registerPicturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.contactor
     * @return the value of tb_warehouse.contactor
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.contactor
     * @param contactor
     *            the value for tb_warehouse.contactor
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.contactor_mobile
     * @return the value of tb_warehouse.contactor_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getContactorMobile() {
        return contactorMobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.contactor_mobile
     * @param contactorMobile
     *            the value for tb_warehouse.contactor_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setContactorMobile(String contactorMobile) {
        this.contactorMobile = contactorMobile == null ? null : contactorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.business_start_time
     * @return the value of tb_warehouse.business_start_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getBusinessStartTime() {
        return businessStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.business_start_time
     * @param businessStartTime
     *            the value for tb_warehouse.business_start_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setBusinessStartTime(String businessStartTime) {
        this.businessStartTime = businessStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.business_end_time
     * @return the value of tb_warehouse.business_end_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getBusinessEndTime() {
        return businessEndTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.business_end_time
     * @param businessEndTime
     *            the value for tb_warehouse.business_end_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setBusinessEndTime(String businessEndTime) {
        this.businessEndTime = businessEndTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.warning_empty_amount
     * @return the value of tb_warehouse.warning_empty_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getWarningEmptyAmount() {
        return warningEmptyAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.warning_empty_amount
     * @param warningEmptyAmount
     *            the value for tb_warehouse.warning_empty_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setWarningEmptyAmount(Integer warningEmptyAmount) {
        this.warningEmptyAmount = warningEmptyAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.warning_occupied_percent
     * @return the value of tb_warehouse.warning_occupied_percent
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Float getWarningOccupiedPercent() {
        return warningOccupiedPercent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.warning_occupied_percent
     * @param warningOccupiedPercent
     *            the value for tb_warehouse.warning_occupied_percent
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setWarningOccupiedPercent(Float warningOccupiedPercent) {
        this.warningOccupiedPercent = warningOccupiedPercent;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.comment
     * @return the value of tb_warehouse.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.comment
     * @param comment
     *            the value for tb_warehouse.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.status
     * @return the value of tb_warehouse.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.status
     * @param status
     *            the value for tb_warehouse.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.reserved
     * @return the value of tb_warehouse.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.reserved
     * @param reserved
     *            the value for tb_warehouse.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.create_user
     * @return the value of tb_warehouse.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.create_user
     * @param createUser
     *            the value for tb_warehouse.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.create_time
     * @return the value of tb_warehouse.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (createTime == null) {
            return null;
        } else {
            return (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.create_time
     * @param createTime
     *            the value for tb_warehouse.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (createTime == null) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.update_user
     * @return the value of tb_warehouse.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.update_user
     * @param updateUser
     *            the value for tb_warehouse.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_warehouse.update_time
     * @return the value of tb_warehouse.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (updateTime == null) {
            return null;
        } else {
            return (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_warehouse.update_time
     * @param updateTime
     *            the value for tb_warehouse.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (updateTime == null) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }

    /**
     * Getter method for property <tt>businessTimeName</tt>.
     * @return property value of businessTimeName
     */
    public String getBusinessTimeName() {
        return businessTimeName;
    }

    /**
     * Setter method for property <tt>businessTimeName</tt>.
     * @param businessTimeName
     *            value to be assigned to property businessTimeName
     */
    public void setBusinessTimeName(String businessTimeName) {
        this.businessTimeName = businessTimeName;
    }

    /**
     * Getter method for property <tt>statusName</tt>.
     * @return property value of statusName
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * Setter method for property <tt>statusName</tt>.
     * @param statusName
     *            value to be assigned to property statusName
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    /**
     * Getter method for property <tt>useRate</tt>.
     * @return property value of useRate
     */
    public String getUseRate() {
        return useRate;
    }

    /**
     * Setter method for property <tt>useRate</tt>.
     * @param useRate
     *            value to be assigned to property useRate
     */
    public void setUseRate(String useRate) {
        this.useRate = useRate;
    }

    /**
     * Getter method for property <tt>customerNum</tt>.
     * @return property value of customerNum
     */
    public String getCustomerNum() {
        return customerNum;
    }

    /**
     * Setter method for property <tt>customerNum</tt>.
     * @param customerNum
     *            value to be assigned to property customerNum
     */
    public void setCustomerNum(String customerNum) {
        this.customerNum = customerNum;
    }

    /**
     * Getter method for property <tt>freeAmount</tt>.
     * @return property value of freeAmount
     */
    public String getFreeAmount() {
        return freeAmount;
    }

    /**
     * Setter method for property <tt>freeAmount</tt>.
     * @param freeAmount
     *            value to be assigned to property freeAmount
     */
    public void setFreeAmount(String freeAmount) {
        this.freeAmount = freeAmount;
    }

    /**
     * Getter method for property <tt>customerList</tt>.
     * @return property value of customerList
     */
    public List<WarehouseLinkCustomerVO> getCustomerList() {
        return customerList;
    }

    /**
     * Setter method for property <tt>customerList</tt>.
     * @param customerList
     *            value to be assigned to property customerList
     */
    public void setCustomerList(List<WarehouseLinkCustomerVO> customerList) {
        this.customerList = customerList;
    }

    /**
     * Getter method for property <tt>warningType</tt>.
     * @return property value of warningType
     */
    public Integer getWarningType() {
        return warningType;
    }

    /**
     * Setter method for property <tt>warningType</tt>.
     * @param warningType
     *            value to be assigned to property warningType
     */
    public void setWarningType(Integer warningType) {
        this.warningType = warningType;
    }

    /**
     * Getter method for property <tt>parentName</tt>.
     * @return property value of parentName
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Setter method for property <tt>parentName</tt>.
     * @param parentName
     *            value to be assigned to property parentName
     */
    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

}
