package com.anji.allways.business.mapper;

import com.anji.allways.business.entity.AppReleaseEntity;

public interface AppReleaseEntityMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_app_release
     * @mbggenerated Thu Sep 21 13:48:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_app_release
     * @mbggenerated Thu Sep 21 13:48:32 CST 2017
     */
    int insert(AppReleaseEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_app_release
     * @mbggenerated Thu Sep 21 13:48:32 CST 2017
     */
    int insertSelective(AppReleaseEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_app_release
     * @mbggenerated Thu Sep 21 13:48:32 CST 2017
     */
    AppReleaseEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_app_release
     * @mbggenerated Thu Sep 21 13:48:32 CST 2017
     */
    int updateByPrimaryKeySelective(AppReleaseEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_app_release
     * @mbggenerated Thu Sep 21 13:48:32 CST 2017
     */
    int updateByPrimaryKey(AppReleaseEntity record);

    AppReleaseEntity selectByTypeDesc(int type);
}
