package com.anji.allways.business.mapper;

import com.anji.allways.business.entity.ConsigneeEntity;

public interface ConsigneeEntityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_consignee
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_consignee
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insert(ConsigneeEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_consignee
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insertSelective(ConsigneeEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_consignee
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    ConsigneeEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_consignee
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(ConsigneeEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_consignee
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKey(ConsigneeEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_consignee
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int selectByUserId(Integer userId);
}
