package com.anji.allways.business.mapper;

import java.util.List;

import com.anji.allways.business.entity.CustomerLinkBrandEntity;

public interface CustomerLinkBrandEntityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_customer_link_brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_customer_link_brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insert(CustomerLinkBrandEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_customer_link_brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insertSelective(CustomerLinkBrandEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_customer_link_brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    CustomerLinkBrandEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_customer_link_brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerLinkBrandEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_customer_link_brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKey(CustomerLinkBrandEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_customer_link_brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    List<String> selectByCustomerId(Integer userId);

    /**
     * 根据客户ID删除相关经营范围
     * @param record
     * @return
     */
    int deleteByCustomerId(Integer customerId);
}
