package com.anji.allways.business.mapper;

import com.anji.allways.business.entity.DeliveryPlanMapEntity;

public interface DeliveryPlanMapEntityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_delivery_plan_map
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_delivery_plan_map
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insert(DeliveryPlanMapEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_delivery_plan_map
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insertSelective(DeliveryPlanMapEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_delivery_plan_map
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    DeliveryPlanMapEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_delivery_plan_map
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(DeliveryPlanMapEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_delivery_plan_map
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKey(DeliveryPlanMapEntity record);
}
