package com.anji.allways.business.mapper;

import java.util.List;
import java.util.Map;

import com.anji.allways.business.entity.DictEntity;
import com.anji.allways.business.vo.DictVO;

public interface DictEntityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_dict
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_dict
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insert(DictEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_dict
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insertSelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_dict
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    DictEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_dict
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_dict
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKey(DictEntity record);

    /**
     * 获取数据字典列表
     * @param typeCode
     * @return
     */
    List<DictVO> queryAllByCode(String typeCode);

    /**
     * 获取数据字典列表--颜色
     * @param typeCode
     * @return
     */
    List<Map<String, Object>> selectByCategoryCode(String typeCode);

    /**
     * 获取颜色数据字典列表
     * @param typeCode
     * @return
     */
    List<DictVO> queryAllByCodeForColor(String typeCode);
}
