package com.anji.allways.business.mapper;

import com.anji.allways.business.entity.OriginalBrandEntity;
import com.anji.allways.business.entity.OriginalBrandEntityExample;
import com.anji.allways.business.entity.OriginalBrandEntityKey;
import org.apache.ibatis.annotations.Param;

public interface OriginalBrandEntityMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int countByExample(OriginalBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int deleteByPrimaryKey(OriginalBrandEntityKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int insert(OriginalBrandEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int insertSelective(OriginalBrandEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    OriginalBrandEntity selectByPrimaryKey(OriginalBrandEntityKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") OriginalBrandEntity record, @Param("example") OriginalBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int updateByExample(@Param("record") OriginalBrandEntity record, @Param("example") OriginalBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int updateByPrimaryKeySelective(OriginalBrandEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    int updateByPrimaryKey(OriginalBrandEntity record);
}
