package com.anji.allways.business.mapper;

import java.util.List;
import java.util.Map;

import com.anji.allways.business.entity.StoragePlanEntity;
import com.anji.allways.business.entity.StorageRecordEntity;
import com.anji.allways.business.vo.StorageRecordVO;

public interface StoragePlanEntityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_storage_plan
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_storage_plan
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insert(StoragePlanEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_storage_plan
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insertSelective(StoragePlanEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_storage_plan
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    StoragePlanEntity selectByPrimaryKey(Integer id);

    // query by plan no
    StoragePlanEntity selectByNo(String no);

    // query plans count
    Integer queryStoragePlanCount(StoragePlanEntity entity);

    // query plans for page
    List<StoragePlanEntity> queryStoragePlans(StoragePlanEntity entity);

    // query records count
    Integer queryStorageRecordCount(StorageRecordEntity entity);

    // query records for page
    List<StorageRecordVO> queryStorageRecords(StorageRecordEntity entity);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_storage_plan
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(StoragePlanEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_storage_plan
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKey(StoragePlanEntity record);

    /**
     * 查询导出入库记录
     * @param entity
     * @param pageNum
     * @param pageRows
     * @return
     */
    List<Map<String, Object>> queryStorageRecordsForExportData(Map<String, Object> map);

    /**
     * 取消入库计划单
     * @param map
     * @return 影响行数
     */
    int cancelStoragePlan(Map<String, Object> map);

    /**
     * 更新入库计划单
     * @param map
     * @return 影响行数
     */
    int updateStoragePlanById(Map<String, Object> map);

    /**
     * 查询导出入库计划单
     * @param entity
     * @param pageNum
     * @param pageRows
     * @return
     */
    List<Map<String, Object>> exportStoragePlanByExcel(Map<String, Object> map);
}
