package com.anji.allways.business.mapper;

import java.util.List;
import java.util.Map;

import com.anji.allways.business.entity.TransportCompanyEntity;
import com.anji.allways.business.vo.DictVO;
import com.anji.allways.business.vo.TransportCompanyVO;

public interface TransportCompanyEntityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_transport_company
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_transport_company
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insert(TransportCompanyEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_transport_company
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insertSelective(TransportCompanyEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_transport_company
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    TransportCompanyVO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_transport_company
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(TransportCompanyEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_transport_company
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKey(TransportCompanyEntity record);

    /**
     * 校验字段值是否重复
     * @param record
     * @return
     */
    int checkRepeatValue(Map<String, Object> map);

    /**
     * 获取运输公司信息下拉列表
     */
    List<DictVO> queryCompanyForDict(Map<String, Object> map);

    /**
     * 分页查询
     * @param berth
     * @return
     */
    List<TransportCompanyVO> queryCompanyInfos(TransportCompanyEntity bean);

    /**
     * 分页查询记录数
     * @param bean
     * @return
     */
    Integer queryCompanyInfosCount(TransportCompanyEntity bean);

    /**
     * 批量激活或停用公司
     * @param map
     * @return
     */
    Integer updateByIdList(Map<String, Object> map);

    /**
     * 编辑运输公司时，更新信息
     * @param bean
     * @return
     */
    int updateByIDForEditCompany(TransportCompanyEntity bean);

    /**
     * check所选运输公司下司机是否已经全部停用
     * @param ID
     *            运输公司ID
     * @return 运输公司名称列表
     */
    List<String> checkCompanyAllDriver(Map<String, Object> map);
}
