package com.anji.allways.business.mapper;

import com.anji.allways.business.entity.UserLinkRoleEntity;

public interface UserLinkRoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_link_role
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_link_role
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insert(UserLinkRoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_link_role
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int insertSelective(UserLinkRoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_link_role
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    UserLinkRoleEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_link_role
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(UserLinkRoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_link_role
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    int updateByPrimaryKey(UserLinkRoleEntity record);
}
