/**
 * anji-allways.com Inc.
 * Copyright (c) 2016-2017 All Rights Reserved.
 */
package com.anji.allways.business.entity;

import java.util.Date;

/**
 * <pre>
 *
 * </pre>
 * @author wangyanjun
 * @version $Id: AdvertisementEntity.java, v 0.1 2017年8月23日 下午5:25:23 wangyanjun Exp $
 */
public class AdvertisementEntity {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     type;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.title
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  title;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  picturePath;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.priority
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  comment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_advertisement.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.id
     * @return the value of tb_advertisement.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.id
     * @param id
     *            the value for tb_advertisement.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.type
     * @return the value of tb_advertisement.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.type
     * @param type
     *            the value for tb_advertisement.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.title
     * @return the value of tb_advertisement.title
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.title
     * @param title
     *            the value for tb_advertisement.title
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.picture_path
     * @return the value of tb_advertisement.picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.picture_path
     * @param picturePath
     *            the value for tb_advertisement.picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.priority
     * @return the value of tb_advertisement.priority
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.priority
     * @param priority
     *            the value for tb_advertisement.priority
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.comment
     * @return the value of tb_advertisement.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.comment
     * @param comment
     *            the value for tb_advertisement.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.create_user
     * @return the value of tb_advertisement.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.create_user
     * @param createUser
     *            the value for tb_advertisement.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.create_time
     * @return the value of tb_advertisement.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (null == createTime) {
            return null;
        }
        return (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.create_time
     * @param createTime
     *            the value for tb_advertisement.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (null == createTime) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.update_user
     * @return the value of tb_advertisement.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.update_user
     * @param updateUser
     *            the value for tb_advertisement.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_advertisement.update_time
     * @return the value of tb_advertisement.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (null == updateTime) {
            return null;
        }
        return (Date) updateTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_advertisement.update_time
     * @param updateTime
     *            the value for tb_advertisement.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (null == updateTime) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }
}
