package com.anji.allways.business.entity;

import java.util.Date;

public class BrandEntity {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    private String  brandInitial;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  brand;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.series
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  series;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.model
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  model;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.announce_year
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  announceYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.logo_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  logoPicturePath;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  comment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_brand.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.id
     * @return the value of tb_brand.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.id
     * @param id
     *            the value for tb_brand.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.brand
     * @return the value of tb_brand.brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.brand
     * @param brand
     *            the value for tb_brand.brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    public String getBrandInitial() {
        return brandInitial;
    }

    public void setBrandInitial(String brandInitial) {
        this.brandInitial = brandInitial;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.series
     * @return the value of tb_brand.series
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.series
     * @param series
     *            the value for tb_brand.series
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.model
     * @return the value of tb_brand.model
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.model
     * @param model
     *            the value for tb_brand.model
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.announce_year
     * @return the value of tb_brand.announce_year
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getAnnounceYear() {
        return announceYear;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.announce_year
     * @param announceYear
     *            the value for tb_brand.announce_year
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setAnnounceYear(String announceYear) {
        this.announceYear = announceYear == null ? null : announceYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.logo_picture_path
     * @return the value of tb_brand.logo_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getLogoPicturePath() {
        return logoPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.logo_picture_path
     * @param logoPicturePath
     *            the value for tb_brand.logo_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setLogoPicturePath(String logoPicturePath) {
        this.logoPicturePath = logoPicturePath == null ? null : logoPicturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.comment
     * @return the value of tb_brand.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.comment
     * @param comment
     *            the value for tb_brand.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.create_user
     * @return the value of tb_brand.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.create_user
     * @param createUser
     *            the value for tb_brand.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.create_time
     * @return the value of tb_brand.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (null == createTime) {
            return null;
        }
        return (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.create_time
     * @param createTime
     *            the value for tb_brand.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (null == createTime) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.update_user
     * @return the value of tb_brand.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.update_user
     * @param updateUser
     *            the value for tb_brand.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_brand.update_time
     * @return the value of tb_brand.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (null == updateTime) {
            return null;
        }
        return (Date) updateTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_brand.update_time
     * @param updateTime
     *            the value for tb_brand.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (null == updateTime) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }
}
