package com.anji.allways.business.entity;

import java.util.Date;

public class ConsigneeEntity {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  mobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_consignee.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  reserved;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.id
     * @return the value of tb_consignee.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.id
     * @param id
     *            the value for tb_consignee.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.mobile
     * @return the value of tb_consignee.mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.mobile
     * @param mobile
     *            the value for tb_consignee.mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.name
     * @return the value of tb_consignee.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.name
     * @param name
     *            the value for tb_consignee.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.create_user
     * @return the value of tb_consignee.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.create_user
     * @param createUser
     *            the value for tb_consignee.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * Getter method for property <tt>userId</tt>.
     * @return property value of userId
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * Setter method for property <tt>userId</tt>.
     * @param userId
     *            value to be assigned to property userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.create_time
     * @return the value of tb_consignee.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (createTime == null) {
            return null;
        } else {
            return (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.create_time
     * @param createTime
     *            the value for tb_consignee.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (createTime == null) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.update_user
     * @return the value of tb_consignee.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.update_user
     * @param updateUser
     *            the value for tb_consignee.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.update_time
     * @return the value of tb_consignee.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (updateTime == null) {
            return null;
        } else {
            return (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.update_time
     * @param updateTime
     *            the value for tb_consignee.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (updateTime == null) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_consignee.reserved
     * @return the value of tb_consignee.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_consignee.reserved
     * @param reserved
     *            the value for tb_consignee.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }
}
