package com.anji.allways.business.entity;

import java.util.Date;

public class CustomerPrivateKeyEntity {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer_private_key.id
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer_private_key.customer_id
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    private String  customerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer_private_key.private_key
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    private String  privateKey;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer_private_key.creator_name
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    private String  creatorName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer_private_key.create_time
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    private Date    createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer_private_key.id
     * @return the value of tb_customer_private_key.id
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer_private_key.id
     * @param id
     *            the value for tb_customer_private_key.id
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer_private_key.customer_id
     * @return the value of tb_customer_private_key.customer_id
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer_private_key.customer_id
     * @param customerId
     *            the value for tb_customer_private_key.customer_id
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer_private_key.private_key
     * @return the value of tb_customer_private_key.private_key
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer_private_key.private_key
     * @param privateKey
     *            the value for tb_customer_private_key.private_key
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer_private_key.creator_name
     * @return the value of tb_customer_private_key.creator_name
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer_private_key.creator_name
     * @param creatorName
     *            the value for tb_customer_private_key.creator_name
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer_private_key.create_time
     * @return the value of tb_customer_private_key.create_time
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public Date getCreateTime() {
        if (null == createTime) {
            return null;
        }
        return (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer_private_key.create_time
     * @param createTime
     *            the value for tb_customer_private_key.create_time
     * @mbggenerated Thu Aug 31 17:06:07 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (null == createTime) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

}
