package com.anji.allways.business.entity;

public class DeliveryPlanMapEntity {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan_map.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan_map.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan_map.child_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer childId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan_map.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  reserved;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan_map.id
     * @return the value of tb_delivery_plan_map.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan_map.id
     * @param id
     *            the value for tb_delivery_plan_map.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan_map.parent_id
     * @return the value of tb_delivery_plan_map.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan_map.parent_id
     * @param parentId
     *            the value for tb_delivery_plan_map.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan_map.child_id
     * @return the value of tb_delivery_plan_map.child_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getChildId() {
        return childId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan_map.child_id
     * @param childId
     *            the value for tb_delivery_plan_map.child_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setChildId(Integer childId) {
        this.childId = childId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan_map.reserved
     * @return the value of tb_delivery_plan_map.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan_map.reserved
     * @param reserved
     *            the value for tb_delivery_plan_map.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }
}
