package com.anji.allways.business.entity;

import java.util.Date;

import com.anji.allways.common.util.PageUtil;

public class DeliveryPlanEntity extends PageUtil {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  no;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     type;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.delivery_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  deliveryType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.delivery_plan_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    deliveryPlanTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.pickup_plan_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    pickupPlanTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.transport_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  transportType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.warehouse_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  warehouseName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.driver_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     driverId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.delivery_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    deliveryTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.consignee_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  consigneeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  customer;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.operator
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  operator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.ship_no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  shipNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.identity_card_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  identityCardPicturePath;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.identity_card_picture_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     identityCardPictureNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.identity_card_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     identityCardStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.check_comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  checkComment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.selfpicker_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  selfpickerPicturePath;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.selfpicker_picture_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     selfpickerPictureNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.is_void
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     isVoid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  reserved;

    /**
     * 仓库ID
     */
    private int     warehouseId;

    /**
     * 行程状态
     */
    private int     routingStatus;

    /**
     * 发运交接现场照片路径
     */
    private String  despatchConfirmPicturePath;

    /**
     * 发运交接现场照片张数
     */
    private Integer despatchConfirmPictureNumber;

    /**
     * 提取状态（0:未提取，1：已提取）
     */
    private int     keyIsTaken;

    /**
     * 送达备注
     */
    private String  acceptComment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     vehicleCount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  transportCompanyName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  customerName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  incomeName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  contactorMobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  provinceName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  cityName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  districtName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  address;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  truckNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  driverName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  driverMobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  telephone;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.id
     * @return the value of tb_delivery_plan.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.id
     * @param id
     *            the value for tb_delivery_plan.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.no
     * @return the value of tb_delivery_plan.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.no
     * @param no
     *            the value for tb_delivery_plan.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.type
     * @return the value of tb_delivery_plan.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.type
     * @param type
     *            the value for tb_delivery_plan.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.parent_id
     * @return the value of tb_delivery_plan.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.parent_id
     * @param parentId
     *            the value for tb_delivery_plan.parent_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.delivery_type
     * @return the value of tb_delivery_plan.delivery_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.delivery_type
     * @param deliveryType
     *            the value for tb_delivery_plan.delivery_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType == null ? null : deliveryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.delivery_plan_time
     * @return the value of tb_delivery_plan.delivery_plan_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getDeliveryPlanTime() {
        if (deliveryPlanTime == null) {
            return null;
        } else {
            return (Date) deliveryPlanTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.delivery_plan_time
     * @param deliveryPlanTime
     *            the value for tb_delivery_plan.delivery_plan_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDeliveryPlanTime(Date deliveryPlanTime) {
        if (deliveryPlanTime == null) {
            this.deliveryPlanTime = null;
        } else {
            this.deliveryPlanTime = (Date) deliveryPlanTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.pickup_plan_time
     * @return the value of tb_delivery_plan.pickup_plan_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getPickupPlanTime() {
        if (pickupPlanTime == null) {
            return null;
        } else {
            return (Date) pickupPlanTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.pickup_plan_time
     * @param pickupPlanTime
     *            the value for tb_delivery_plan.pickup_plan_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setPickupPlanTime(Date pickupPlanTime) {
        if (pickupPlanTime == null) {
            this.pickupPlanTime = null;
        } else {
            this.pickupPlanTime = (Date) pickupPlanTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.transport_type
     * @return the value of tb_delivery_plan.transport_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getTransportType() {
        return transportType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.transport_type
     * @param transportType
     *            the value for tb_delivery_plan.transport_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setTransportType(String transportType) {
        this.transportType = transportType == null ? null : transportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.warehouse_name
     * @return the value of tb_delivery_plan.warehouse_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.warehouse_name
     * @param warehouseName
     *            the value for tb_delivery_plan.warehouse_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    public int getDriverId() {
        return driverId;
    }

    public void setDriverId(int driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.delivery_time
     * @return the value of tb_delivery_plan.delivery_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getDeliveryTime() {
        if (deliveryTime == null) {
            return null;
        } else {
            return (Date) deliveryTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.delivery_time
     * @param deliveryTime
     *            the value for tb_delivery_plan.delivery_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDeliveryTime(Date deliveryTime) {
        if (deliveryTime == null) {
            this.deliveryTime = null;
        } else {
            this.deliveryTime = (Date) deliveryTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.consignee_mobile
     * @return the value of tb_delivery_plan.consignee_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getConsigneeId() {
        return consigneeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.consignee_mobile
     * @param consigneeMobile
     *            the value for tb_delivery_plan.consignee_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setConsigneeId(String consigneeId) {
        this.consigneeId = consigneeId == null ? null : consigneeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.status
     * @return the value of tb_delivery_plan.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.status
     * @param status
     *            the value for tb_delivery_plan.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.create_time
     * @return the value of tb_delivery_plan.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (createTime == null) {
            return null;
        } else {
            return (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.create_time
     * @param createTime
     *            the value for tb_delivery_plan.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (createTime == null) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.customer
     * @return the value of tb_delivery_plan.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.customer
     * @param customer
     *            the value for tb_delivery_plan.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.operator
     * @return the value of tb_delivery_plan.operator
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.operator
     * @param operator
     *            the value for tb_delivery_plan.operator
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.ship_no
     * @return the value of tb_delivery_plan.ship_no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getShipNo() {
        return shipNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.ship_no
     * @param shipNo
     *            the value for tb_delivery_plan.ship_no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setShipNo(String shipNo) {
        this.shipNo = shipNo == null ? null : shipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.identity_card_picture_path
     * @return the value of tb_delivery_plan.identity_card_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getIdentityCardPicturePath() {
        return identityCardPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.identity_card_picture_path
     * @param identityCardPicturePath
     *            the value for tb_delivery_plan.identity_card_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setIdentityCardPicturePath(String identityCardPicturePath) {
        this.identityCardPicturePath = identityCardPicturePath == null ? null : identityCardPicturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.identity_card_picture_number
     * @return the value of tb_delivery_plan.identity_card_picture_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getIdentityCardPictureNumber() {
        return identityCardPictureNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.identity_card_picture_number
     * @param identityCardPictureNumber
     *            the value for tb_delivery_plan.identity_card_picture_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setIdentityCardPictureNumber(int identityCardPictureNumber) {
        this.identityCardPictureNumber = identityCardPictureNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.identity_card_status
     * @return the value of tb_delivery_plan.identity_card_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getIdentityCardStatus() {
        return identityCardStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.identity_card_status
     * @param identityCardStatus
     *            the value for tb_delivery_plan.identity_card_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setIdentityCardStatus(int identityCardStatus) {
        this.identityCardStatus = identityCardStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.check_comment
     * @return the value of tb_delivery_plan.check_comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCheckComment() {
        return checkComment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.check_comment
     * @param checkComment
     *            the value for tb_delivery_plan.check_comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCheckComment(String checkComment) {
        this.checkComment = checkComment == null ? null : checkComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.selfpicker_picture_path
     * @return the value of tb_delivery_plan.selfpicker_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getSelfpickerPicturePath() {
        return selfpickerPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.selfpicker_picture_path
     * @param selfpickerPicturePath
     *            the value for tb_delivery_plan.selfpicker_picture_path
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setSelfpickerPicturePath(String selfpickerPicturePath) {
        this.selfpickerPicturePath = selfpickerPicturePath == null ? null : selfpickerPicturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.selfpicker_picture_number
     * @return the value of tb_delivery_plan.selfpicker_picture_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getSelfpickerPictureNumber() {
        return selfpickerPictureNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.selfpicker_picture_number
     * @param selfpickerPictureNumber
     *            the value for tb_delivery_plan.selfpicker_picture_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setSelfpickerPictureNumber(int selfpickerPictureNumber) {
        this.selfpickerPictureNumber = selfpickerPictureNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.is_void
     * @return the value of tb_delivery_plan.is_void
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getIsVoid() {
        return isVoid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.is_void
     * @param isVoid
     *            the value for tb_delivery_plan.is_void
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setIsVoid(int isVoid) {
        this.isVoid = isVoid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.create_user
     * @return the value of tb_delivery_plan.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.create_user
     * @param createUser
     *            the value for tb_delivery_plan.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.update_user
     * @return the value of tb_delivery_plan.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.update_user
     * @param updateUser
     *            the value for tb_delivery_plan.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.update_time
     * @return the value of tb_delivery_plan.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (updateTime == null) {
            return null;
        } else {
            return (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.update_time
     * @param updateTime
     *            the value for tb_delivery_plan.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (updateTime == null) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_delivery_plan.reserved
     * @return the value of tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_delivery_plan.reserved
     * @param reserved
     *            the value for tb_delivery_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }

    /**
     * Getter method for property <tt>warehouseId</tt>.
     * @return property value of warehouseId
     */
    public int getWarehouseId() {
        return warehouseId;
    }

    /**
     * Setter method for property <tt>warehouseId</tt>.
     * @param warehouseId
     *            value to be assigned to property warehouseId
     */
    public void setWarehouseId(int warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * Getter method for property <tt>routingStatus</tt>.
     * @return property value of routingStatus
     */
    public int getRoutingStatus() {
        return routingStatus;
    }

    /**
     * Setter method for property <tt>routingStatus</tt>.
     * @param routingStatus
     *            value to be assigned to property routingStatus
     */
    public void setRoutingStatus(int routingStatus) {
        this.routingStatus = routingStatus;
    }

    /**
     * Getter method for property <tt>vehicleCount</tt>.
     * @return property value of vehicleCount
     */
    public int getVehicleCount() {
        return vehicleCount;
    }

    /**
     * Setter method for property <tt>vehicleCount</tt>.
     * @param vehicleCount
     *            value to be assigned to property vehicleCount
     */
    public void setVehicleCount(int vehicleCount) {
        this.vehicleCount = vehicleCount;
    }

    /**
     * Getter method for property <tt>transportCompanyName</tt>.
     * @return property value of transportCompanyName
     */
    public String getTransportCompanyName() {
        return transportCompanyName;
    }

    /**
     * Setter method for property <tt>transportCompanyName</tt>.
     * @param transportCompanyName
     *            value to be assigned to property transportCompanyName
     */
    public void setTransportCompanyName(String transportCompanyName) {
        this.transportCompanyName = transportCompanyName;
    }

    /**
     * Getter method for property <tt>customerName</tt>.
     * @return property value of customerName
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Setter method for property <tt>customerName</tt>.
     * @param customerName
     *            value to be assigned to property customerName
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * Getter method for property <tt>incomeName</tt>.
     * @return property value of incomeName
     */
    public String getIncomeName() {
        return incomeName;
    }

    /**
     * Setter method for property <tt>incomeName</tt>.
     * @param incomeName
     *            value to be assigned to property incomeName
     */
    public void setIncomeName(String incomeName) {
        this.incomeName = incomeName;
    }

    /**
     * Getter method for property <tt>contactorMobile</tt>.
     * @return property value of contactorMobile
     */
    public String getContactorMobile() {
        return contactorMobile;
    }

    /**
     * Setter method for property <tt>contactorMobile</tt>.
     * @param contactorMobile
     *            value to be assigned to property contactorMobile
     */
    public void setContactorMobile(String contactorMobile) {
        this.contactorMobile = contactorMobile;
    }

    /**
     * Getter method for property <tt>provinceName</tt>.
     * @return property value of provinceName
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * Setter method for property <tt>provinceName</tt>.
     * @param provinceName
     *            value to be assigned to property provinceName
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * Getter method for property <tt>cityName</tt>.
     * @return property value of cityName
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Setter method for property <tt>cityName</tt>.
     * @param cityName
     *            value to be assigned to property cityName
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * Getter method for property <tt>districtName</tt>.
     * @return property value of districtName
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * Setter method for property <tt>districtName</tt>.
     * @param districtName
     *            value to be assigned to property districtName
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * Getter method for property <tt>address</tt>.
     * @return property value of address
     */
    public String getAddress() {
        return address;
    }

    /**
     * Setter method for property <tt>address</tt>.
     * @param address
     *            value to be assigned to property address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter method for property <tt>truckNumber</tt>.
     * @return property value of truckNumber
     */
    public String getTruckNumber() {
        return truckNumber;
    }

    /**
     * Setter method for property <tt>truckNumber</tt>.
     * @param truckNumber
     *            value to be assigned to property truckNumber
     */
    public void setTruckNumber(String truckNumber) {
        this.truckNumber = truckNumber;
    }

    /**
     * Getter method for property <tt>driverName</tt>.
     * @return property value of driverName
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Setter method for property <tt>driverName</tt>.
     * @param driverName
     *            value to be assigned to property driverName
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    /**
     * Getter method for property <tt>driverMobile</tt>.
     * @return property value of driverMobile
     */
    public String getDriverMobile() {
        return driverMobile;
    }

    /**
     * Setter method for property <tt>driverMobile</tt>.
     * @param driverMobile
     *            value to be assigned to property driverMobile
     */
    public void setDriverMobile(String driverMobile) {
        this.driverMobile = driverMobile;
    }

    /**
     * Getter method for property <tt>despatchConfirmPicturePath</tt>.
     * @return property value of despatchConfirmPicturePath
     */
    public String getDespatchConfirmPicturePath() {
        return despatchConfirmPicturePath;
    }

    /**
     * Setter method for property <tt>despatchConfirmPicturePath</tt>.
     * @param despatchConfirmPicturePath
     *            value to be assigned to property despatchConfirmPicturePath
     */
    public void setDespatchConfirmPicturePath(String despatchConfirmPicturePath) {
        this.despatchConfirmPicturePath = despatchConfirmPicturePath;
    }

    /**
     * Getter method for property <tt>despatchConfirmPictureNumber</tt>.
     * @return property value of despatchConfirmPictureNumber
     */
    public Integer getDespatchConfirmPictureNumber() {
        return despatchConfirmPictureNumber;
    }

    /**
     * Setter method for property <tt>despatchConfirmPictureNumber</tt>.
     * @param despatchConfirmPictureNumber
     *            value to be assigned to property despatchConfirmPictureNumber
     */
    public void setDespatchConfirmPictureNumber(Integer despatchConfirmPictureNumber) {
        this.despatchConfirmPictureNumber = despatchConfirmPictureNumber;
    }

    /**
     * Getter method for property <tt>keyIsTaken</tt>.
     * @return property value of keyIsTaken
     */
    public int getKeyIsTaken() {
        return keyIsTaken;
    }

    /**
     * Setter method for property <tt>keyIsTaken</tt>.
     * @param keyIsTaken
     *            value to be assigned to property keyIsTaken
     */
    public void setKeyIsTaken(int keyIsTaken) {
        this.keyIsTaken = keyIsTaken;
    }

    /**
     * Getter method for property <tt>acceptComment</tt>.
     * @return property value of acceptComment
     */
    public String getAcceptComment() {
        return acceptComment;
    }

    /**
     * Setter method for property <tt>acceptComment</tt>.
     * @param acceptComment
     *            value to be assigned to property acceptComment
     */
    public void setAcceptComment(String acceptComment) {
        this.acceptComment = acceptComment;
    }

    /**
     * Getter method for property <tt>telephone</tt>.
     * @return property value of telephone
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * Setter method for property <tt>telephone</tt>.
     * @param telephone
     *            value to be assigned to property telephone
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
}
