package com.anji.allways.business.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OriginalBrandEntityExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    private String         orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    private boolean        distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    private List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public OriginalBrandEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        private List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBrandnameIsNull() {
            addCriterion("brandName is null");
            return (Criteria) this;
        }

        public Criteria andBrandnameIsNotNull() {
            addCriterion("brandName is not null");
            return (Criteria) this;
        }

        public Criteria andBrandnameEqualTo(String value) {
            addCriterion("brandName =", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameNotEqualTo(String value) {
            addCriterion("brandName <>", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameGreaterThan(String value) {
            addCriterion("brandName >", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameGreaterThanOrEqualTo(String value) {
            addCriterion("brandName >=", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameLessThan(String value) {
            addCriterion("brandName <", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameLessThanOrEqualTo(String value) {
            addCriterion("brandName <=", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameLike(String value) {
            addCriterion("brandName like", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameNotLike(String value) {
            addCriterion("brandName not like", value, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameIn(List<String> values) {
            addCriterion("brandName in", values, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameNotIn(List<String> values) {
            addCriterion("brandName not in", values, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameBetween(String value1, String value2) {
            addCriterion("brandName between", value1, value2, "brandname");
            return (Criteria) this;
        }

        public Criteria andBrandnameNotBetween(String value1, String value2) {
            addCriterion("brandName not between", value1, value2, "brandname");
            return (Criteria) this;
        }

        public Criteria andModelyearIsNull() {
            addCriterion("modelYear is null");
            return (Criteria) this;
        }

        public Criteria andModelyearIsNotNull() {
            addCriterion("modelYear is not null");
            return (Criteria) this;
        }

        public Criteria andModelyearEqualTo(String value) {
            addCriterion("modelYear =", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearNotEqualTo(String value) {
            addCriterion("modelYear <>", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearGreaterThan(String value) {
            addCriterion("modelYear >", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearGreaterThanOrEqualTo(String value) {
            addCriterion("modelYear >=", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearLessThan(String value) {
            addCriterion("modelYear <", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearLessThanOrEqualTo(String value) {
            addCriterion("modelYear <=", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearLike(String value) {
            addCriterion("modelYear like", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearNotLike(String value) {
            addCriterion("modelYear not like", value, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearIn(List<String> values) {
            addCriterion("modelYear in", values, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearNotIn(List<String> values) {
            addCriterion("modelYear not in", values, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearBetween(String value1, String value2) {
            addCriterion("modelYear between", value1, value2, "modelyear");
            return (Criteria) this;
        }

        public Criteria andModelyearNotBetween(String value1, String value2) {
            addCriterion("modelYear not between", value1, value2, "modelyear");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameIsNull() {
            addCriterion("subModelName is null");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameIsNotNull() {
            addCriterion("subModelName is not null");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameEqualTo(String value) {
            addCriterion("subModelName =", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameNotEqualTo(String value) {
            addCriterion("subModelName <>", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameGreaterThan(String value) {
            addCriterion("subModelName >", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameGreaterThanOrEqualTo(String value) {
            addCriterion("subModelName >=", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameLessThan(String value) {
            addCriterion("subModelName <", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameLessThanOrEqualTo(String value) {
            addCriterion("subModelName <=", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameLike(String value) {
            addCriterion("subModelName like", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameNotLike(String value) {
            addCriterion("subModelName not like", value, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameIn(List<String> values) {
            addCriterion("subModelName in", values, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameNotIn(List<String> values) {
            addCriterion("subModelName not in", values, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameBetween(String value1, String value2) {
            addCriterion("subModelName between", value1, value2, "submodelname");
            return (Criteria) this;
        }

        public Criteria andSubmodelnameNotBetween(String value1, String value2) {
            addCriterion("subModelName not between", value1, value2, "submodelname");
            return (Criteria) this;
        }

        public Criteria andVersionnameIsNull() {
            addCriterion("versionName is null");
            return (Criteria) this;
        }

        public Criteria andVersionnameIsNotNull() {
            addCriterion("versionName is not null");
            return (Criteria) this;
        }

        public Criteria andVersionnameEqualTo(String value) {
            addCriterion("versionName =", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotEqualTo(String value) {
            addCriterion("versionName <>", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameGreaterThan(String value) {
            addCriterion("versionName >", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameGreaterThanOrEqualTo(String value) {
            addCriterion("versionName >=", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameLessThan(String value) {
            addCriterion("versionName <", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameLessThanOrEqualTo(String value) {
            addCriterion("versionName <=", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameLike(String value) {
            addCriterion("versionName like", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotLike(String value) {
            addCriterion("versionName not like", value, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameIn(List<String> values) {
            addCriterion("versionName in", values, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotIn(List<String> values) {
            addCriterion("versionName not in", values, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameBetween(String value1, String value2) {
            addCriterion("versionName between", value1, value2, "versionname");
            return (Criteria) this;
        }

        public Criteria andVersionnameNotBetween(String value1, String value2) {
            addCriterion("versionName not between", value1, value2, "versionname");
            return (Criteria) this;
        }

        public Criteria andManfnameIsNull() {
            addCriterion("manfName is null");
            return (Criteria) this;
        }

        public Criteria andManfnameIsNotNull() {
            addCriterion("manfName is not null");
            return (Criteria) this;
        }

        public Criteria andManfnameEqualTo(String value) {
            addCriterion("manfName =", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameNotEqualTo(String value) {
            addCriterion("manfName <>", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameGreaterThan(String value) {
            addCriterion("manfName >", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameGreaterThanOrEqualTo(String value) {
            addCriterion("manfName >=", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameLessThan(String value) {
            addCriterion("manfName <", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameLessThanOrEqualTo(String value) {
            addCriterion("manfName <=", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameLike(String value) {
            addCriterion("manfName like", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameNotLike(String value) {
            addCriterion("manfName not like", value, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameIn(List<String> values) {
            addCriterion("manfName in", values, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameNotIn(List<String> values) {
            addCriterion("manfName not in", values, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameBetween(String value1, String value2) {
            addCriterion("manfName between", value1, value2, "manfname");
            return (Criteria) this;
        }

        public Criteria andManfnameNotBetween(String value1, String value2) {
            addCriterion("manfName not between", value1, value2, "manfname");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameIsNull() {
            addCriterion("vehicleTypeName is null");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameIsNotNull() {
            addCriterion("vehicleTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameEqualTo(String value) {
            addCriterion("vehicleTypeName =", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameNotEqualTo(String value) {
            addCriterion("vehicleTypeName <>", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameGreaterThan(String value) {
            addCriterion("vehicleTypeName >", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameGreaterThanOrEqualTo(String value) {
            addCriterion("vehicleTypeName >=", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameLessThan(String value) {
            addCriterion("vehicleTypeName <", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameLessThanOrEqualTo(String value) {
            addCriterion("vehicleTypeName <=", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameLike(String value) {
            addCriterion("vehicleTypeName like", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameNotLike(String value) {
            addCriterion("vehicleTypeName not like", value, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameIn(List<String> values) {
            addCriterion("vehicleTypeName in", values, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameNotIn(List<String> values) {
            addCriterion("vehicleTypeName not in", values, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameBetween(String value1, String value2) {
            addCriterion("vehicleTypeName between", value1, value2, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andVehicletypenameNotBetween(String value1, String value2) {
            addCriterion("vehicleTypeName not between", value1, value2, "vehicletypename");
            return (Criteria) this;
        }

        public Criteria andManfpropnameIsNull() {
            addCriterion("manfPropName is null");
            return (Criteria) this;
        }

        public Criteria andManfpropnameIsNotNull() {
            addCriterion("manfPropName is not null");
            return (Criteria) this;
        }

        public Criteria andManfpropnameEqualTo(String value) {
            addCriterion("manfPropName =", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameNotEqualTo(String value) {
            addCriterion("manfPropName <>", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameGreaterThan(String value) {
            addCriterion("manfPropName >", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameGreaterThanOrEqualTo(String value) {
            addCriterion("manfPropName >=", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameLessThan(String value) {
            addCriterion("manfPropName <", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameLessThanOrEqualTo(String value) {
            addCriterion("manfPropName <=", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameLike(String value) {
            addCriterion("manfPropName like", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameNotLike(String value) {
            addCriterion("manfPropName not like", value, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameIn(List<String> values) {
            addCriterion("manfPropName in", values, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameNotIn(List<String> values) {
            addCriterion("manfPropName not in", values, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameBetween(String value1, String value2) {
            addCriterion("manfPropName between", value1, value2, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andManfpropnameNotBetween(String value1, String value2) {
            addCriterion("manfPropName not between", value1, value2, "manfpropname");
            return (Criteria) this;
        }

        public Criteria andBodytypenameIsNull() {
            addCriterion("bodyTypeName is null");
            return (Criteria) this;
        }

        public Criteria andBodytypenameIsNotNull() {
            addCriterion("bodyTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andBodytypenameEqualTo(String value) {
            addCriterion("bodyTypeName =", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameNotEqualTo(String value) {
            addCriterion("bodyTypeName <>", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameGreaterThan(String value) {
            addCriterion("bodyTypeName >", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameGreaterThanOrEqualTo(String value) {
            addCriterion("bodyTypeName >=", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameLessThan(String value) {
            addCriterion("bodyTypeName <", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameLessThanOrEqualTo(String value) {
            addCriterion("bodyTypeName <=", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameLike(String value) {
            addCriterion("bodyTypeName like", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameNotLike(String value) {
            addCriterion("bodyTypeName not like", value, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameIn(List<String> values) {
            addCriterion("bodyTypeName in", values, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameNotIn(List<String> values) {
            addCriterion("bodyTypeName not in", values, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameBetween(String value1, String value2) {
            addCriterion("bodyTypeName between", value1, value2, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andBodytypenameNotBetween(String value1, String value2) {
            addCriterion("bodyTypeName not between", value1, value2, "bodytypename");
            return (Criteria) this;
        }

        public Criteria andSegmentnameIsNull() {
            addCriterion("segmentName is null");
            return (Criteria) this;
        }

        public Criteria andSegmentnameIsNotNull() {
            addCriterion("segmentName is not null");
            return (Criteria) this;
        }

        public Criteria andSegmentnameEqualTo(String value) {
            addCriterion("segmentName =", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameNotEqualTo(String value) {
            addCriterion("segmentName <>", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameGreaterThan(String value) {
            addCriterion("segmentName >", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameGreaterThanOrEqualTo(String value) {
            addCriterion("segmentName >=", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameLessThan(String value) {
            addCriterion("segmentName <", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameLessThanOrEqualTo(String value) {
            addCriterion("segmentName <=", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameLike(String value) {
            addCriterion("segmentName like", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameNotLike(String value) {
            addCriterion("segmentName not like", value, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameIn(List<String> values) {
            addCriterion("segmentName in", values, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameNotIn(List<String> values) {
            addCriterion("segmentName not in", values, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameBetween(String value1, String value2) {
            addCriterion("segmentName between", value1, value2, "segmentname");
            return (Criteria) this;
        }

        public Criteria andSegmentnameNotBetween(String value1, String value2) {
            addCriterion("segmentName not between", value1, value2, "segmentname");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameIsNull() {
            addCriterion("engineTypeName is null");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameIsNotNull() {
            addCriterion("engineTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameEqualTo(String value) {
            addCriterion("engineTypeName =", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameNotEqualTo(String value) {
            addCriterion("engineTypeName <>", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameGreaterThan(String value) {
            addCriterion("engineTypeName >", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameGreaterThanOrEqualTo(String value) {
            addCriterion("engineTypeName >=", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameLessThan(String value) {
            addCriterion("engineTypeName <", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameLessThanOrEqualTo(String value) {
            addCriterion("engineTypeName <=", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameLike(String value) {
            addCriterion("engineTypeName like", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameNotLike(String value) {
            addCriterion("engineTypeName not like", value, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameIn(List<String> values) {
            addCriterion("engineTypeName in", values, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameNotIn(List<String> values) {
            addCriterion("engineTypeName not in", values, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameBetween(String value1, String value2) {
            addCriterion("engineTypeName between", value1, value2, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andEnginetypenameNotBetween(String value1, String value2) {
            addCriterion("engineTypeName not between", value1, value2, "enginetypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameIsNull() {
            addCriterion("tranTypeName is null");
            return (Criteria) this;
        }

        public Criteria andTrantypenameIsNotNull() {
            addCriterion("tranTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andTrantypenameEqualTo(String value) {
            addCriterion("tranTypeName =", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameNotEqualTo(String value) {
            addCriterion("tranTypeName <>", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameGreaterThan(String value) {
            addCriterion("tranTypeName >", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameGreaterThanOrEqualTo(String value) {
            addCriterion("tranTypeName >=", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameLessThan(String value) {
            addCriterion("tranTypeName <", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameLessThanOrEqualTo(String value) {
            addCriterion("tranTypeName <=", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameLike(String value) {
            addCriterion("tranTypeName like", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameNotLike(String value) {
            addCriterion("tranTypeName not like", value, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameIn(List<String> values) {
            addCriterion("tranTypeName in", values, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameNotIn(List<String> values) {
            addCriterion("tranTypeName not in", values, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameBetween(String value1, String value2) {
            addCriterion("tranTypeName between", value1, value2, "trantypename");
            return (Criteria) this;
        }

        public Criteria andTrantypenameNotBetween(String value1, String value2) {
            addCriterion("tranTypeName not between", value1, value2, "trantypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameIsNull() {
            addCriterion("fuelTypeName is null");
            return (Criteria) this;
        }

        public Criteria andFueltypenameIsNotNull() {
            addCriterion("fuelTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andFueltypenameEqualTo(String value) {
            addCriterion("fuelTypeName =", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameNotEqualTo(String value) {
            addCriterion("fuelTypeName <>", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameGreaterThan(String value) {
            addCriterion("fuelTypeName >", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameGreaterThanOrEqualTo(String value) {
            addCriterion("fuelTypeName >=", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameLessThan(String value) {
            addCriterion("fuelTypeName <", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameLessThanOrEqualTo(String value) {
            addCriterion("fuelTypeName <=", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameLike(String value) {
            addCriterion("fuelTypeName like", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameNotLike(String value) {
            addCriterion("fuelTypeName not like", value, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameIn(List<String> values) {
            addCriterion("fuelTypeName in", values, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameNotIn(List<String> values) {
            addCriterion("fuelTypeName not in", values, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameBetween(String value1, String value2) {
            addCriterion("fuelTypeName between", value1, value2, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andFueltypenameNotBetween(String value1, String value2) {
            addCriterion("fuelTypeName not between", value1, value2, "fueltypename");
            return (Criteria) this;
        }

        public Criteria andLaunchdateIsNull() {
            addCriterion("launchDate is null");
            return (Criteria) this;
        }

        public Criteria andLaunchdateIsNotNull() {
            addCriterion("launchDate is not null");
            return (Criteria) this;
        }

        public Criteria andLaunchdateEqualTo(String value) {
            addCriterion("launchDate =", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateNotEqualTo(String value) {
            addCriterion("launchDate <>", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateGreaterThan(String value) {
            addCriterion("launchDate >", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateGreaterThanOrEqualTo(String value) {
            addCriterion("launchDate >=", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateLessThan(String value) {
            addCriterion("launchDate <", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateLessThanOrEqualTo(String value) {
            addCriterion("launchDate <=", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateLike(String value) {
            addCriterion("launchDate like", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateNotLike(String value) {
            addCriterion("launchDate not like", value, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateIn(List<String> values) {
            addCriterion("launchDate in", values, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateNotIn(List<String> values) {
            addCriterion("launchDate not in", values, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateBetween(String value1, String value2) {
            addCriterion("launchDate between", value1, value2, "launchdate");
            return (Criteria) this;
        }

        public Criteria andLaunchdateNotBetween(String value1, String value2) {
            addCriterion("launchDate not between", value1, value2, "launchdate");
            return (Criteria) this;
        }

        public Criteria andMsrpIsNull() {
            addCriterion("msrp is null");
            return (Criteria) this;
        }

        public Criteria andMsrpIsNotNull() {
            addCriterion("msrp is not null");
            return (Criteria) this;
        }

        public Criteria andMsrpEqualTo(String value) {
            addCriterion("msrp =", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpNotEqualTo(String value) {
            addCriterion("msrp <>", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpGreaterThan(String value) {
            addCriterion("msrp >", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpGreaterThanOrEqualTo(String value) {
            addCriterion("msrp >=", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpLessThan(String value) {
            addCriterion("msrp <", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpLessThanOrEqualTo(String value) {
            addCriterion("msrp <=", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpLike(String value) {
            addCriterion("msrp like", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpNotLike(String value) {
            addCriterion("msrp not like", value, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpIn(List<String> values) {
            addCriterion("msrp in", values, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpNotIn(List<String> values) {
            addCriterion("msrp not in", values, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpBetween(String value1, String value2) {
            addCriterion("msrp between", value1, value2, "msrp");
            return (Criteria) this;
        }

        public Criteria andMsrpNotBetween(String value1, String value2) {
            addCriterion("msrp not between", value1, value2, "msrp");
            return (Criteria) this;
        }

        public Criteria andChangesnameIsNull() {
            addCriterion("changesName is null");
            return (Criteria) this;
        }

        public Criteria andChangesnameIsNotNull() {
            addCriterion("changesName is not null");
            return (Criteria) this;
        }

        public Criteria andChangesnameEqualTo(String value) {
            addCriterion("changesName =", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameNotEqualTo(String value) {
            addCriterion("changesName <>", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameGreaterThan(String value) {
            addCriterion("changesName >", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameGreaterThanOrEqualTo(String value) {
            addCriterion("changesName >=", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameLessThan(String value) {
            addCriterion("changesName <", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameLessThanOrEqualTo(String value) {
            addCriterion("changesName <=", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameLike(String value) {
            addCriterion("changesName like", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameNotLike(String value) {
            addCriterion("changesName not like", value, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameIn(List<String> values) {
            addCriterion("changesName in", values, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameNotIn(List<String> values) {
            addCriterion("changesName not in", values, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameBetween(String value1, String value2) {
            addCriterion("changesName between", value1, value2, "changesname");
            return (Criteria) this;
        }

        public Criteria andChangesnameNotBetween(String value1, String value2) {
            addCriterion("changesName not between", value1, value2, "changesname");
            return (Criteria) this;
        }

        public Criteria andOnproductflagIsNull() {
            addCriterion("onProductFlag is null");
            return (Criteria) this;
        }

        public Criteria andOnproductflagIsNotNull() {
            addCriterion("onProductFlag is not null");
            return (Criteria) this;
        }

        public Criteria andOnproductflagEqualTo(String value) {
            addCriterion("onProductFlag =", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagNotEqualTo(String value) {
            addCriterion("onProductFlag <>", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagGreaterThan(String value) {
            addCriterion("onProductFlag >", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagGreaterThanOrEqualTo(String value) {
            addCriterion("onProductFlag >=", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagLessThan(String value) {
            addCriterion("onProductFlag <", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagLessThanOrEqualTo(String value) {
            addCriterion("onProductFlag <=", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagLike(String value) {
            addCriterion("onProductFlag like", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagNotLike(String value) {
            addCriterion("onProductFlag not like", value, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagIn(List<String> values) {
            addCriterion("onProductFlag in", values, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagNotIn(List<String> values) {
            addCriterion("onProductFlag not in", values, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagBetween(String value1, String value2) {
            addCriterion("onProductFlag between", value1, value2, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnproductflagNotBetween(String value1, String value2) {
            addCriterion("onProductFlag not between", value1, value2, "onproductflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagIsNull() {
            addCriterion("onSaleFlag is null");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagIsNotNull() {
            addCriterion("onSaleFlag is not null");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagEqualTo(String value) {
            addCriterion("onSaleFlag =", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagNotEqualTo(String value) {
            addCriterion("onSaleFlag <>", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagGreaterThan(String value) {
            addCriterion("onSaleFlag >", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagGreaterThanOrEqualTo(String value) {
            addCriterion("onSaleFlag >=", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagLessThan(String value) {
            addCriterion("onSaleFlag <", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagLessThanOrEqualTo(String value) {
            addCriterion("onSaleFlag <=", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagLike(String value) {
            addCriterion("onSaleFlag like", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagNotLike(String value) {
            addCriterion("onSaleFlag not like", value, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagIn(List<String> values) {
            addCriterion("onSaleFlag in", values, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagNotIn(List<String> values) {
            addCriterion("onSaleFlag not in", values, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagBetween(String value1, String value2) {
            addCriterion("onSaleFlag between", value1, value2, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andOnsaleflagNotBetween(String value1, String value2) {
            addCriterion("onSaleFlag not between", value1, value2, "onsaleflag");
            return (Criteria) this;
        }

        public Criteria andCarcolorIsNull() {
            addCriterion("carColor is null");
            return (Criteria) this;
        }

        public Criteria andCarcolorIsNotNull() {
            addCriterion("carColor is not null");
            return (Criteria) this;
        }

        public Criteria andCarcolorEqualTo(String value) {
            addCriterion("carColor =", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotEqualTo(String value) {
            addCriterion("carColor <>", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorGreaterThan(String value) {
            addCriterion("carColor >", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorGreaterThanOrEqualTo(String value) {
            addCriterion("carColor >=", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorLessThan(String value) {
            addCriterion("carColor <", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorLessThanOrEqualTo(String value) {
            addCriterion("carColor <=", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorLike(String value) {
            addCriterion("carColor like", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotLike(String value) {
            addCriterion("carColor not like", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorIn(List<String> values) {
            addCriterion("carColor in", values, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotIn(List<String> values) {
            addCriterion("carColor not in", values, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorBetween(String value1, String value2) {
            addCriterion("carColor between", value1, value2, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotBetween(String value1, String value2) {
            addCriterion("carColor not between", value1, value2, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tb_original_brand
     * @mbggenerated Mon Sep 18 20:52:55 CST 2017
     */
    public static class Criterion {
        private String  condition;
        private Object  value;
        private Object  secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String  typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tb_original_brand
     * @mbggenerated do_not_delete_during_merge Mon Sep 18 14:09:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
