package com.anji.allways.business.entity;

import java.util.Date;

public class ShipReceiptEntity {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  no;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.delivery_plan_no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  deliveryPlanNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.depart_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    departTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.truck_driver_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer truckDriverId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  customer;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.receiving_address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  receivingAddress;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  reserved;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.creator_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  creatorName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_ship_receipt.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.id
     * @return the value of tb_ship_receipt.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */

    private Integer isPrinted;

    /**
     * @return the isPrinted
     */
    public Integer getIsPrinted() {
        return isPrinted;
    }

    /**
     * @param isPrinted
     *            the isPrinted to set
     */
    public void setIsPrinted(Integer isPrinted) {
        this.isPrinted = isPrinted;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.id
     * @param id
     *            the value for tb_ship_receipt.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.no
     * @return the value of tb_ship_receipt.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.no
     * @param no
     *            the value for tb_ship_receipt.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.delivery_plan_no
     * @return the value of tb_ship_receipt.delivery_plan_no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getDeliveryPlanNo() {
        return deliveryPlanNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.delivery_plan_no
     * @param deliveryPlanNo
     *            the value for tb_ship_receipt.delivery_plan_no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDeliveryPlanNo(String deliveryPlanNo) {
        this.deliveryPlanNo = deliveryPlanNo == null ? null : deliveryPlanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.depart_time
     * @return the value of tb_ship_receipt.depart_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getDepartTime() {
        if (null == departTime) {
            return null;
        }
        return (Date) departTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.depart_time
     * @param departTime
     *            the value for tb_ship_receipt.depart_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDepartTime(Date departTime) {
        if (null == departTime) {
            this.departTime = null;
        } else {
            this.departTime = (Date) departTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.truck_driver_id
     * @return the value of tb_ship_receipt.truck_driver_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getTruckDriverId() {
        return truckDriverId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.truck_driver_id
     * @param truckDriverId
     *            the value for tb_ship_receipt.truck_driver_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setTruckDriverId(Integer truckDriverId) {
        this.truckDriverId = truckDriverId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.customer
     * @return the value of tb_ship_receipt.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.customer
     * @param customer
     *            the value for tb_ship_receipt.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.receiving_address
     * @return the value of tb_ship_receipt.receiving_address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReceivingAddress() {
        return receivingAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.receiving_address
     * @param receivingAddress
     *            the value for tb_ship_receipt.receiving_address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReceivingAddress(String receivingAddress) {
        this.receivingAddress = receivingAddress == null ? null : receivingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.reserved
     * @return the value of tb_ship_receipt.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.reserved
     * @param reserved
     *            the value for tb_ship_receipt.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.creator_name
     * @return the value of tb_ship_receipt.creator_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.creator_name
     * @param creatorName
     *            the value for tb_ship_receipt.creator_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_ship_receipt.create_time
     * @return the value of tb_ship_receipt.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (null == createTime) {
            return null;
        }
        return (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_ship_receipt.create_time
     * @param createTime
     *            the value for tb_ship_receipt.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (null == createTime) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }
}
