package com.anji.allways.business.entity;

import java.util.Date;
import java.util.List;

import com.anji.allways.common.util.PageUtil;

public class StoragePlanEntity extends PageUtil {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        no;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        customer;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.warehouse_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        warehouseName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.warehouse_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       warehouseId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.operator
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        operator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_storage_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        reserved;

    /**
     * 入库时间
     */
    private Date          storageTime;

    /**
     * 状态̬
     */
    private int           status;

    /**
     * 客户id
     */
    private Integer       customerId;

    /**
     * 创建开始时间
     */
    private String        createStartTime;

    /**
     * 创建结束时间
     */
    private String        createEndTime;

    /**
     * 入库状态（查询使用）
     */
    private String        statusSearch;

    /**
     * 入库车辆数
     */
    private Integer       carNum;

    /**
     * 入库计划单状态名称
     */
    private String        statusName;

    /**
     * 所有层级ID
     */
    private List<Integer> idList;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.id
     * @return the value of tb_storage_plan.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.id
     * @param id
     *            the value for tb_storage_plan.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.no
     * @return the value of tb_storage_plan.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.no
     * @param no
     *            the value for tb_storage_plan.no
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.customer
     * @return the value of tb_storage_plan.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.customer
     * @param customer
     *            the value for tb_storage_plan.customer
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.warehouse_name
     * @return the value of tb_storage_plan.warehouse_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.warehouse_name
     * @param warehouseName
     *            the value for tb_storage_plan.warehouse_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.warehouse_id
     * @return the value of tb_storage_plan.warehouse_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.warehouse_id
     * @param warehouseId
     *            the value for tb_storage_plan.warehouse_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.operator
     * @return the value of tb_storage_plan.operator
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.operator
     * @param operator
     *            the value for tb_storage_plan.operator
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.create_user
     * @return the value of tb_storage_plan.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.create_user
     * @param createUser
     *            the value for tb_storage_plan.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.create_time
     * @return the value of tb_storage_plan.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (null == createTime) {
            return null;
        }
        return (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.create_time
     * @param createTime
     *            the value for tb_storage_plan.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (null == createTime) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.update_user
     * @return the value of tb_storage_plan.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.update_user
     * @param updateUser
     *            the value for tb_storage_plan.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.update_time
     * @return the value of tb_storage_plan.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (null == updateTime) {
            return null;
        }
        return (Date) updateTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.update_time
     * @param updateTime
     *            the value for tb_storage_plan.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (null == updateTime) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.reserved
     * @return the value of tb_storage_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.reserved
     * @param reserved
     *            the value for tb_storage_plan.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * Getter method for property <tt>createStartTime</tt>.
     * @return property value of createStartTime
     */
    public String getCreateStartTime() {
        return createStartTime;
    }

    /**
     * Setter method for property <tt>createStartTime</tt>.
     * @param createStartTime
     *            value to be assigned to property createStartTime
     */
    public void setCreateStartTime(String createStartTime) {
        this.createStartTime = createStartTime;
    }

    /**
     * Getter method for property <tt>createEndTime</tt>.
     * @return property value of createEndTime
     */
    public String getCreateEndTime() {
        return createEndTime;
    }

    /**
     * Setter method for property <tt>createEndTime</tt>.
     * @param createEndTime
     *            value to be assigned to property createEndTime
     */
    public void setCreateEndTime(String createEndTime) {
        this.createEndTime = createEndTime;
    }

    /**
     * Getter method for property <tt>statusSearch</tt>.
     * @return property value of statusSearch
     */
    public String getStatusSearch() {
        return statusSearch;
    }

    /**
     * Setter method for property <tt>statusSearch</tt>.
     * @param statusSearch
     *            value to be assigned to property statusSearch
     */
    public void setStatusSearch(String statusSearch) {
        this.statusSearch = statusSearch;
    }

    /**
     * Getter method for property <tt>carNum</tt>.
     * @return property value of carNum
     */
    public Integer getCarNum() {
        return carNum;
    }

    /**
     * Setter method for property <tt>carNum</tt>.
     * @param carNum
     *            value to be assigned to property carNum
     */
    public void setCarNum(Integer carNum) {
        this.carNum = carNum;
    }

    /**
     * Getter method for property <tt>statusName</tt>.
     * @return property value of statusName
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * Setter method for property <tt>statusName</tt>.
     * @param statusName
     *            value to be assigned to property statusName
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    /**
     * Getter method for property <tt>idList</tt>.
     * @return property value of idList
     */
    public List<Integer> getIdList() {
        return idList;
    }

    /**
     * Setter method for property <tt>idList</tt>.
     * @param idList
     *            value to be assigned to property idList
     */
    public void setIdList(List<Integer> idList) {
        this.idList = idList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_storage_plan.update_time
     * @return the value of tb_storage_plan.storage_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getStorageTime() {
        if (null == storageTime) {
            return null;
        }
        return (Date) storageTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_storage_plan.update_time
     * @param updateTime
     *            the value for tb_storage_plan.storage_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setStorageTime(Date storageTime) {
        if (null == storageTime) {
            this.storageTime = null;
        } else {
            this.storageTime = (Date) storageTime.clone();
        }
    }

    /**
     * Getter method for property <tt>customerId</tt>.
     *
     * @return property value of customerId
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * Setter method for property <tt>customerId</tt>.
     *
     * @param customerId value to be assigned to property customerId
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}
