package com.anji.allways.business.entity;

import java.util.Date;

import com.anji.allways.common.util.PageUtil;

public class TransportCompanyEntity extends PageUtil {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.provinceName
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  provinceName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.provinceCode
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  provinceCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.cityName
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  cityName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.cityCode
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  cityCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.districtName
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  districtName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.districtCode
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  districtCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  address;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.contactor
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  contactor;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.contactor_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  contactorMobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.driver_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer driverAmount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.favorable_rate
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Float   favorableRate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.ontime_rate
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Float   ontimeRate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  comment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_transport_company.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    updateTime;

    // ----------查询使用------
    /**
     * 创建开始时间
     */
    private String  createStartTime;

    /**
     * 创建结束时间
     */
    private String  createEndTime;

    /**
     * 好评率开始
     */
    private String  favorableRateStart;

    /**
     * 好评率结束
     */
    private String  favorableRateEnd;

    /**
     * 及时率开始
     */
    private String  ontimeRateStart;

    /**
     * 及时率结束
     */
    private String  ontimeRateEnd;

    /**
     * 运输公司状态查询使用
     */
    private String  searchStatus;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.id
     * @return the value of tb_transport_company.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.id
     * @param id
     *            the value for tb_transport_company.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.name
     * @return the value of tb_transport_company.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.name
     * @param name
     *            the value for tb_transport_company.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * Getter method for property <tt>provinceName</tt>.
     * @return property value of provinceName
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * Setter method for property <tt>provinceName</tt>.
     * @param provinceName
     *            value to be assigned to property provinceName
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * Getter method for property <tt>provinceCode</tt>.
     * @return property value of provinceCode
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * Setter method for property <tt>provinceCode</tt>.
     * @param provinceCode
     *            value to be assigned to property provinceCode
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * Getter method for property <tt>cityName</tt>.
     * @return property value of cityName
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Setter method for property <tt>cityName</tt>.
     * @param cityName
     *            value to be assigned to property cityName
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * Getter method for property <tt>cityCode</tt>.
     * @return property value of cityCode
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * Setter method for property <tt>cityCode</tt>.
     * @param cityCode
     *            value to be assigned to property cityCode
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * Getter method for property <tt>districtName</tt>.
     * @return property value of districtName
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * Setter method for property <tt>districtName</tt>.
     * @param districtName
     *            value to be assigned to property districtName
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * Getter method for property <tt>districtCode</tt>.
     * @return property value of districtCode
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * Setter method for property <tt>districtCode</tt>.
     * @param districtCode
     *            value to be assigned to property districtCode
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.address
     * @return the value of tb_transport_company.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.address
     * @param address
     *            the value for tb_transport_company.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.contactor
     * @return the value of tb_transport_company.contactor
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.contactor
     * @param contactor
     *            the value for tb_transport_company.contactor
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.contactor_mobile
     * @return the value of tb_transport_company.contactor_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getContactorMobile() {
        return contactorMobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.contactor_mobile
     * @param contactorMobile
     *            the value for tb_transport_company.contactor_mobile
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setContactorMobile(String contactorMobile) {
        this.contactorMobile = contactorMobile == null ? null : contactorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.driver_amount
     * @return the value of tb_transport_company.driver_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getDriverAmount() {
        return driverAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.driver_amount
     * @param driverAmount
     *            the value for tb_transport_company.driver_amount
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDriverAmount(Integer driverAmount) {
        this.driverAmount = driverAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.status
     * @return the value of tb_transport_company.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.status
     * @param status
     *            the value for tb_transport_company.status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.favorable_rate
     * @return the value of tb_transport_company.favorable_rate
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Float getFavorableRate() {
        return favorableRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.favorable_rate
     * @param favorableRate
     *            the value for tb_transport_company.favorable_rate
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setFavorableRate(Float favorableRate) {
        this.favorableRate = favorableRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.ontime_rate
     * @return the value of tb_transport_company.ontime_rate
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Float getOntimeRate() {
        return ontimeRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.ontime_rate
     * @param ontimeRate
     *            the value for tb_transport_company.ontime_rate
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setOntimeRate(Float ontimeRate) {
        this.ontimeRate = ontimeRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.comment
     * @return the value of tb_transport_company.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.comment
     * @param comment
     *            the value for tb_transport_company.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.create_user
     * @return the value of tb_transport_company.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.create_user
     * @param createUser
     *            the value for tb_transport_company.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.create_time
     * @return the value of tb_transport_company.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (null == createTime) {
            return null;
        }
        return (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.create_time
     * @param createTime
     *            the value for tb_transport_company.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (null == createTime) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.update_user
     * @return the value of tb_transport_company.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.update_user
     * @param updateUser
     *            the value for tb_transport_company.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_transport_company.update_time
     * @return the value of tb_transport_company.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (null == updateTime) {
            return null;
        }
        return (Date) updateTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_transport_company.update_time
     * @param updateTime
     *            the value for tb_transport_company.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (null == updateTime) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }

    /**
     * Getter method for property <tt>createStartTime</tt>.
     * @return property value of createStartTime
     */
    public String getCreateStartTime() {
        return createStartTime;
    }

    /**
     * Setter method for property <tt>createStartTime</tt>.
     * @param createStartTime
     *            value to be assigned to property createStartTime
     */
    public void setCreateStartTime(String createStartTime) {
        this.createStartTime = createStartTime;
    }

    /**
     * Getter method for property <tt>createEndTime</tt>.
     * @return property value of createEndTime
     */
    public String getCreateEndTime() {
        return createEndTime;
    }

    /**
     * Setter method for property <tt>createEndTime</tt>.
     * @param createEndTime
     *            value to be assigned to property createEndTime
     */
    public void setCreateEndTime(String createEndTime) {
        this.createEndTime = createEndTime;
    }

    /**
     * Getter method for property <tt>favorableRateStart</tt>.
     * @return property value of favorableRateStart
     */
    public String getFavorableRateStart() {
        return favorableRateStart;
    }

    /**
     * Setter method for property <tt>favorableRateStart</tt>.
     * @param favorableRateStart
     *            value to be assigned to property favorableRateStart
     */
    public void setFavorableRateStart(String favorableRateStart) {
        this.favorableRateStart = favorableRateStart;
    }

    /**
     * Getter method for property <tt>favorableRateEnd</tt>.
     * @return property value of favorableRateEnd
     */
    public String getFavorableRateEnd() {
        return favorableRateEnd;
    }

    /**
     * Setter method for property <tt>favorableRateEnd</tt>.
     * @param favorableRateEnd
     *            value to be assigned to property favorableRateEnd
     */
    public void setFavorableRateEnd(String favorableRateEnd) {
        this.favorableRateEnd = favorableRateEnd;
    }

    /**
     * Getter method for property <tt>ontimeRateStart</tt>.
     * @return property value of ontimeRateStart
     */
    public String getOntimeRateStart() {
        return ontimeRateStart;
    }

    /**
     * Setter method for property <tt>ontimeRateStart</tt>.
     * @param ontimeRateStart
     *            value to be assigned to property ontimeRateStart
     */
    public void setOntimeRateStart(String ontimeRateStart) {
        this.ontimeRateStart = ontimeRateStart;
    }

    /**
     * Getter method for property <tt>ontimeRateEnd</tt>.
     * @return property value of ontimeRateEnd
     */
    public String getOntimeRateEnd() {
        return ontimeRateEnd;
    }

    /**
     * Setter method for property <tt>ontimeRateEnd</tt>.
     * @param ontimeRateEnd
     *            value to be assigned to property ontimeRateEnd
     */
    public void setOntimeRateEnd(String ontimeRateEnd) {
        this.ontimeRateEnd = ontimeRateEnd;
    }

    /**
     * Getter method for property <tt>searchStatus</tt>.
     * @return property value of searchStatus
     */
    public String getSearchStatus() {
        return searchStatus;
    }

    /**
     * Setter method for property <tt>searchStatus</tt>.
     * @param searchStatus
     *            value to be assigned to property searchStatus
     */
    public void setSearchStatus(String searchStatus) {
        this.searchStatus = searchStatus;
    }
}
