package com.anji.allways.business.entity;

import java.util.Date;
import java.util.List;

import com.anji.allways.common.util.PageUtil;

public class UserEntity extends PageUtil {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.account_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        accountName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.password
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.customer_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       customerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.is_valid
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           isValid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.locked
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           locked;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.description
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.credentials_salt
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        credentialsSalt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.create_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        createName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        updateUser;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        reserved;

    /**
     * 权限系统用户id
     */
    private Integer       permissionUserId;

    /**
     * 账户类型 0:普通 1：管理员
     */
    private Integer       accountType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        telephone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        address;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        customer;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       consigneeId;

    /**
     * 锁定状态（查询使用）
     */
    private String        lockedSearch;

    /**
     * 联系人
     */
    private String        contactor;

    /**
     * 联系电话
     */
    private String        contactorMobile;

    /**
     * 客户名称
     */
    private String        customerName;

    /**
     * 创建开始时间
     */
    private String        createStartTime;

    /**
     * 创建结束时间
     */
    private String        createEndTime;

    /**
     * 层级IDList
     */
    private List<Integer> idList;

    /**
     * 锁定状态名称
     */
    private String        lockedName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.id
     * @return the value of tb_user.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.id
     * @param id
     *            the value for tb_user.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.name
     * @return the value of tb_user.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.name
     * @param name
     *            the value for tb_user.name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.account_name
     * @return the value of tb_user.account_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.account_name
     * @param accountName
     *            the value for tb_user.account_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.password
     * @return the value of tb_user.password
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.password
     * @param password
     *            the value for tb_user.password
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.customer_id
     * @return the value of tb_user.customer_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.customer_id
     * @param customerId
     *            the value for tb_user.customer_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.type
     * @return the value of tb_user.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.type
     * @param type
     *            the value for tb_user.type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.is_valid
     * @return the value of tb_user.is_valid
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.is_valid
     * @param isValid
     *            the value for tb_user.is_valid
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setIsValid(int isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.locked
     * @return the value of tb_user.locked
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.locked
     * @param locked
     *            the value for tb_user.locked
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setLocked(int locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.description
     * @return the value of tb_user.description
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.description
     * @param description
     *            the value for tb_user.description
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.credentials_salt
     * @return the value of tb_user.credentials_salt
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCredentialsSalt() {
        return credentialsSalt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.credentials_salt
     * @param credentialsSalt
     *            the value for tb_user.credentials_salt
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCredentialsSalt(String credentialsSalt) {
        this.credentialsSalt = credentialsSalt == null ? null : credentialsSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.create_name
     * @return the value of tb_user.create_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.create_name
     * @param createName
     *            the value for tb_user.create_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.create_time
     * @return the value of tb_user.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (createTime == null) {
            return null;
        } else {
            return (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.create_time
     * @param createTime
     *            the value for tb_user.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (createTime == null) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.update_user
     * @return the value of tb_user.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.update_user
     * @param updateUser
     *            the value for tb_user.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.update_time
     * @return the value of tb_user.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (updateTime == null) {
            return null;
        } else {
            return (Date) updateTime.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.update_time
     * @param updateTime
     *            the value for tb_user.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (updateTime == null) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.reserved
     * @return the value of tb_user.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.reserved
     * @param reserved
     *            the value for tb_user.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }

    /**
     * Getter method for property <tt>permissionUserId</tt>.
     * @return property value of permissionUserId
     */
    public Integer getPermissionUserId() {
        return permissionUserId;
    }

    /**
     * Setter method for property <tt>permissionUserId</tt>.
     * @param permissionUserId
     *            value to be assigned to property permissionUserId
     */
    public void setPermissionUserId(Integer permissionUserId) {
        this.permissionUserId = permissionUserId;
    }

    /**
     * Getter method for property <tt>accountType</tt>.
     * @return property value of accountType
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * Setter method for property <tt>accountType</tt>.
     * @param accountType
     *            value to be assigned to property accountType
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * Getter method for property <tt>telephone</tt>.
     * @return property value of telephone
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * Setter method for property <tt>telephone</tt>.
     * @param telephone
     *            value to be assigned to property telephone
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * Getter method for property <tt>address</tt>.
     * @return property value of address
     */
    public String getAddress() {
        return address;
    }

    /**
     * Setter method for property <tt>address</tt>.
     * @param address
     *            value to be assigned to property address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter method for property <tt>customer</tt>.
     * @return property value of customer
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Setter method for property <tt>customer</tt>.
     * @param customer
     *            value to be assigned to property customer
     */
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    /**
     * Getter method for property <tt>consigneeId</tt>.
     * @return property value of consigneeId
     */
    public Integer getConsigneeId() {
        return consigneeId;
    }

    /**
     * Setter method for property <tt>consigneeId</tt>.
     * @param consigneeId
     *            value to be assigned to property consigneeId
     */
    public void setConsigneeId(Integer consigneeId) {
        this.consigneeId = consigneeId;
    }

    /**
     * Getter method for property <tt>contactor</tt>.
     * @return property value of contactor
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * Setter method for property <tt>contactor</tt>.
     * @param contactor
     *            value to be assigned to property contactor
     */
    public void setContactor(String contactor) {
        this.contactor = contactor;
    }

    /**
     * Getter method for property <tt>contactorMobile</tt>.
     * @return property value of contactorMobile
     */
    public String getContactorMobile() {
        return contactorMobile;
    }

    /**
     * Setter method for property <tt>contactorMobile</tt>.
     * @param contactorMobile
     *            value to be assigned to property contactorMobile
     */
    public void setContactorMobile(String contactorMobile) {
        this.contactorMobile = contactorMobile;
    }

    /**
     * Getter method for property <tt>customerName</tt>.
     * @return property value of customerName
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Setter method for property <tt>customerName</tt>.
     * @param customerName
     *            value to be assigned to property customerName
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * Getter method for property <tt>createStartTime</tt>.
     * @return property value of createStartTime
     */
    public String getCreateStartTime() {
        return createStartTime;
    }

    /**
     * Setter method for property <tt>createStartTime</tt>.
     * @param createStartTime
     *            value to be assigned to property createStartTime
     */
    public void setCreateStartTime(String createStartTime) {
        this.createStartTime = createStartTime;
    }

    /**
     * Getter method for property <tt>createEndTime</tt>.
     * @return property value of createEndTime
     */
    public String getCreateEndTime() {
        return createEndTime;
    }

    /**
     * Setter method for property <tt>createEndTime</tt>.
     * @param createEndTime
     *            value to be assigned to property createEndTime
     */
    public void setCreateEndTime(String createEndTime) {
        this.createEndTime = createEndTime;
    }

    /**
     * Getter method for property <tt>idList</tt>.
     * @return property value of idList
     */
    public List<Integer> getIdList() {
        return idList;
    }

    /**
     * Setter method for property <tt>idList</tt>.
     * @param idList
     *            value to be assigned to property idList
     */
    public void setIdList(List<Integer> idList) {
        this.idList = idList;
    }

    /**
     * Getter method for property <tt>lockedSearch</tt>.
     * @return property value of lockedSearch
     */
    public String getLockedSearch() {
        return lockedSearch;
    }

    /**
     * Setter method for property <tt>lockedSearch</tt>.
     * @param lockedSearch
     *            value to be assigned to property lockedSearch
     */
    public void setLockedSearch(String lockedSearch) {
        this.lockedSearch = lockedSearch;
    }

    /**
     * Getter method for property <tt>lockedName</tt>.
     * @return property value of lockedName
     */
    public String getLockedName() {
        return lockedName;
    }

    /**
     * Setter method for property <tt>lockedName</tt>.
     * @param lockedName
     *            value to be assigned to property lockedName
     */
    public void setLockedName(String lockedName) {
        this.lockedName = lockedName;
    }

}
