package com.anji.allways.business.entity;

import java.util.Date;

public class UserLinkRoleEntity {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_link_role.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_link_role.user_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_link_role.role_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_link_role.creator_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  creatorName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_link_role.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_link_role.id
     * @return the value of tb_user_link_role.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_link_role.id
     * @param id
     *            the value for tb_user_link_role.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_link_role.user_id
     * @return the value of tb_user_link_role.user_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_link_role.user_id
     * @param userId
     *            the value for tb_user_link_role.user_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_link_role.role_id
     * @return the value of tb_user_link_role.role_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_link_role.role_id
     * @param roleId
     *            the value for tb_user_link_role.role_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_link_role.creator_name
     * @return the value of tb_user_link_role.creator_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_link_role.creator_name
     * @param creatorName
     *            the value for tb_user_link_role.creator_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_link_role.create_time
     * @return the value of tb_user_link_role.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (createTime == null) {
            return null;
        } else {
            return (Date) createTime.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_link_role.create_time
     * @param createTime
     *            the value for tb_user_link_role.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (createTime == null) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }
}
