package com.anji.allways.business.entity;

import java.util.Date;

public class UserInfoEntity {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer id;

    /**
     * 用户主id
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.sex
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int     sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.birthday
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    birthday;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.telephone
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  telephone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.email
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  email;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  reserved;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date    createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_info.create_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String  createName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.id
     * @return the value of tb_user_info.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.id
     * @param id
     *            the value for tb_user_info.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter method for property <tt>userId</tt>.
     * @return property value of userId
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * Setter method for property <tt>userId</tt>.
     * @param userId
     *            value to be assigned to property userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.sex
     * @return the value of tb_user_info.sex
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.sex
     * @param sex
     *            the value for tb_user_info.sex
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setSex(int sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.birthday
     * @return the value of tb_user_info.birthday
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getBirthday() {
        if (birthday == null) {
            return null;
        } else {
            return (Date) birthday.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.birthday
     * @param birthday
     *            the value for tb_user_info.birthday
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setBirthday(Date birthday) {
        if (birthday == null) {
            this.birthday = null;
        } else {
            this.birthday = (Date) birthday.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.telephone
     * @return the value of tb_user_info.telephone
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.telephone
     * @param telephone
     *            the value for tb_user_info.telephone
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.email
     * @return the value of tb_user_info.email
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.email
     * @param email
     *            the value for tb_user_info.email
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.address
     * @return the value of tb_user_info.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.address
     * @param address
     *            the value for tb_user_info.address
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.reserved
     * @return the value of tb_user_info.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.reserved
     * @param reserved
     *            the value for tb_user_info.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.create_time
     * @return the value of tb_user_info.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (createTime == null) {
            return null;
        }
        return (Date) createTime.clone();
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.create_time
     * @param createTime
     *            the value for tb_user_info.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (createTime == null) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }

    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_info.create_name
     * @return the value of tb_user_info.create_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_info.create_name
     * @param createName
     *            the value for tb_user_info.create_name
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }
}
