package com.anji.allways.business.entity;

import java.util.Date;
import java.util.List;

import com.anji.allways.common.util.PageUtil;

public class VehicleEntity extends PageUtil {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.warehouse_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       warehouseId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.dealer_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       dealerId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.vin
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        vin;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        brand;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.series
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        series;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.model
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        model;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.announce_year
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        announceYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.standard_color_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       standardColorId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.manufacturer_color
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        manufacturerColor;

    private String        picturePath;

    private Integer       pictureNumber;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.license_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        licenseNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.registration_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        registrationNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.vehicle_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           vehicleType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.info
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        info;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        comment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.vehicle_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           vehicleStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.quality_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           qualityStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.lock_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           lockStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       createUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       updateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        reserved;

    /**
     * 预入库商品车id
     */
    private Integer       storageVehicleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        standardColor;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        warehouseName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        location;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        customer;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        userName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          planTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        contactorMobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        logoPicturePath;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           storagePlanId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private int           deliveryPlanId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          storageTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        operatorName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Date          deliveryTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        businessStartTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        businessendtime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        transportNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        transportType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        pickupSelfTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       orderId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private String        orderNo;
    // 入库开始时间
    private String        storageStartTime;
    // 入库结束时间
    private String        storageEndTime;
    // 出库开始时间
    private String        deliveryStartTime;
    // 出库结束时间
    private String        deliveryEndTime;
    // 收车开始时间
    private String        receivedStartTime;
    // 收车结束时间
    private String        receivedEndTime;
    // 收车时间
    private String        receivedTime;

    /**
     * 车辆状态
     */
    private String        vehicleStatusSearch;

    /**
     * 质量状态
     */
    private String        qualityStatusSearch;

    /**
     * 锁定状态
     */
    private String        lockStatusSearch;

    /**
     * 客户ID
     */
    private Integer       customerId;

    /**
     * 所有层级ID
     */
    private List<Integer> idList;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    private Integer       deliveryId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.id
     * @return the value of tb_vehicle.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.id
     * @param id
     *            the value for tb_vehicle.id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.warehouse_id
     * @return the value of tb_vehicle.warehouse_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.warehouse_id
     * @param warehouseId
     *            the value for tb_vehicle.warehouse_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.dealer_id
     * @return the value of tb_vehicle.dealer_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.dealer_id
     * @param dealerId
     *            the value for tb_vehicle.dealer_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.vin
     * @return the value of tb_vehicle.vin
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getVin() {
        if (vin == null) {
            vin = "";
        }
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.vin
     * @param vin
     *            the value for tb_vehicle.vin
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.brand
     * @return the value of tb_vehicle.brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getBrand() {
        if (brand == null) {
            brand = "";
        }
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.brand
     * @param brand
     *            the value for tb_vehicle.brand
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.series
     * @return the value of tb_vehicle.series
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getSeries() {
        if (series == null) {
            series = "";
        }
        return series;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.series
     * @param series
     *            the value for tb_vehicle.series
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.model
     * @return the value of tb_vehicle.model
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getModel() {
        if (model == null) {
            model = "";
        }
        return model;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.model
     * @param model
     *            the value for tb_vehicle.model
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * Getter method for property <tt>announceYear</tt>.
     * @return property value of announceYear
     */
    public String getAnnounceYear() {
        if (announceYear == null) {
            announceYear = "";
        }
        return announceYear;
    }

    /**
     * Setter method for property <tt>announceYear</tt>.
     * @param announceYear
     *            value to be assigned to property announceYear
     */
    public void setAnnounceYear(String announceYear) {
        this.announceYear = announceYear;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.standard_color_id
     * @return the value of tb_vehicle.standard_color_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getStandardColorId() {
        return standardColorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.standard_color_id
     * @param standardColorId
     *            the value for tb_vehicle.standard_color_id
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setStandardColorId(Integer standardColorId) {
        this.standardColorId = standardColorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.manufacturer_color
     * @return the value of tb_vehicle.manufacturer_color
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getManufacturerColor() {
        if (manufacturerColor == null) {
            manufacturerColor = "";
        }
        return manufacturerColor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.manufacturer_color
     * @param manufacturerColor
     *            the value for tb_vehicle.manufacturer_color
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setManufacturerColor(String manufacturerColor) {
        this.manufacturerColor = manufacturerColor == null ? null : manufacturerColor.trim();
    }

    public String getPicturePath() {
        if (picturePath == null) {
            picturePath = "";
        }
        return picturePath;
    }

    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

    public Integer getPictureNumber() {
        return pictureNumber;
    }

    public void setPictureNumber(Integer pictureNumber) {
        this.pictureNumber = pictureNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.license_number
     * @return the value of tb_vehicle.license_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getLicenseNumber() {
        if (licenseNumber == null) {
            licenseNumber = "";
        }
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.license_number
     * @param licenseNumber
     *            the value for tb_vehicle.license_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber == null ? null : licenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.registration_number
     * @return the value of tb_vehicle.registration_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getRegistrationNumber() {
        if (registrationNumber == null) {
            registrationNumber = "";
        }
        return registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.registration_number
     * @param registrationNumber
     *            the value for tb_vehicle.registration_number
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber == null ? null : registrationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.vehicle_type
     * @return the value of tb_vehicle.vehicle_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.vehicle_type
     * @param vehicleType
     *            the value for tb_vehicle.vehicle_type
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setVehicleType(int vehicleType) {
        this.vehicleType = vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.info
     * @return the value of tb_vehicle.info
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getInfo() {
        if (info == null) {
            info = "";
        }
        return info;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.info
     * @param info
     *            the value for tb_vehicle.info
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.comment
     * @return the value of tb_vehicle.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getComment() {
        if (comment == null) {
            comment = "";
        }
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.comment
     * @param comment
     *            the value for tb_vehicle.comment
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.vehicle_status
     * @return the value of tb_vehicle.vehicle_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getVehicleStatus() {
        return vehicleStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.vehicle_status
     * @param vehicleStatus
     *            the value for tb_vehicle.vehicle_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setVehicleStatus(int vehicleStatus) {
        this.vehicleStatus = vehicleStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.quality_status
     * @return the value of tb_vehicle.quality_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getQualityStatus() {
        return qualityStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.quality_status
     * @param qualityStatus
     *            the value for tb_vehicle.quality_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setQualityStatus(int qualityStatus) {
        this.qualityStatus = qualityStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.lock_status
     * @return the value of tb_vehicle.lock_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public int getLockStatus() {
        return lockStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.lock_status
     * @param lockStatus
     *            the value for tb_vehicle.lock_status
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setLockStatus(int lockStatus) {
        this.lockStatus = lockStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.create_user
     * @return the value of tb_vehicle.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.create_user
     * @param createUser
     *            the value for tb_vehicle.create_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.create_time
     * @return the value of tb_vehicle.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getCreateTime() {
        if (createTime == null) {
            return null;
        } else {
            return (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.create_time
     * @param createTime
     *            the value for tb_vehicle.create_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        if (createTime == null) {
            this.createTime = null;
        } else {
            this.createTime = (Date) createTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.update_user
     * @return the value of tb_vehicle.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.update_user
     * @param updateUser
     *            the value for tb_vehicle.update_user
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.update_time
     * @return the value of tb_vehicle.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public Date getUpdateTime() {
        if (updateTime == null) {
            return null;
        } else {
            return (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.update_time
     * @param updateTime
     *            the value for tb_vehicle.update_time
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        if (updateTime == null) {
            this.updateTime = null;
        } else {
            this.updateTime = (Date) updateTime.clone();
        }
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_vehicle.reserved
     * @return the value of tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public String getReserved() {
        if (reserved == null) {
            reserved = "";
        }
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_vehicle.reserved
     * @param reserved
     *            the value for tb_vehicle.reserved
     * @mbggenerated Wed Aug 23 17:12:20 CST 2017
     */
    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }

    /**
     * Getter method for property <tt>standardColor</tt>.
     * @return property value of standardColor
     */
    public String getStandardColor() {
        if (standardColor == null) {
            standardColor = "";
        }
        return standardColor;
    }

    /**
     * Setter method for property <tt>standardColor</tt>.
     * @param standardColor
     *            value to be assigned to property standardColor
     */
    public void setStandardColor(String standardColor) {
        this.standardColor = standardColor;
    }

    /**
     * Getter method for property <tt>warehouseName</tt>.
     * @return property value of warehouseName
     */
    public String getWarehouseName() {
        if (warehouseName == null) {
            warehouseName = "";
        }
        return warehouseName;
    }

    /**
     * Setter method for property <tt>warehouseName</tt>.
     * @param warehouseName
     *            value to be assigned to property warehouseName
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    /**
     * Getter method for property <tt>location</tt>.
     * @return property value of location
     */
    public String getLocation() {
        if (location == null) {
            location = "";
        }
        return location;
    }

    /**
     * Setter method for property <tt>location</tt>.
     * @param location
     *            value to be assigned to property location
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Getter method for property <tt>customer</tt>.
     * @return property value of customer
     */
    public String getCustomer() {
        if (customer == null) {
            customer = "";
        }
        return customer;
    }

    /**
     * Setter method for property <tt>customer</tt>.
     * @param customer
     *            value to be assigned to property customer
     */
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    /**
     * Getter method for property <tt>userName</tt>.
     * @return property value of userName
     */
    public String getUserName() {
        if (userName == null) {
            userName = "";
        }
        return userName;
    }

    /**
     * Setter method for property <tt>userName</tt>.
     * @param userName
     *            value to be assigned to property userName
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter method for property <tt>planTime</tt>.
     * @return property value of planTime
     */
    public Date getPlanTime() {
        if (null == planTime) {
            return null;
        }
        return (Date) planTime.clone();
    }

    /**
     * Setter method for property <tt>planTime</tt>.
     * @param planTime
     *            value to be assigned to property planTime
     */
    public void setPlanTime(Date planTime) {
        if (null == planTime) {
            this.planTime = null;
        } else {
            this.planTime = (Date) planTime.clone();
        }
    }

    /**
     * Getter method for property <tt>contactorMobile</tt>.
     * @return property value of contactorMobile
     */
    public String getContactorMobile() {
        if (contactorMobile == null) {
            contactorMobile = "";
        }
        return contactorMobile;
    }

    /**
     * Setter method for property <tt>contactorMobile</tt>.
     * @param contactorMobile
     *            value to be assigned to property contactorMobile
     */
    public void setContactorMobile(String contactorMobile) {
        this.contactorMobile = contactorMobile;
    }

    /**
     * Getter method for property <tt>logoPicturePath</tt>.
     * @return property value of logoPicturePath
     */
    public String getLogoPicturePath() {
        if (logoPicturePath == null) {
            logoPicturePath = "";
        }
        return logoPicturePath;
    }

    /**
     * Setter method for property <tt>logoPicturePath</tt>.
     * @param logoPicturePath
     *            value to be assigned to property logoPicturePath
     */
    public void setLogoPicturePath(String logoPicturePath) {
        this.logoPicturePath = logoPicturePath;
    }

    /**
     * Getter method for property <tt>storagePlanId</tt>.
     * @return property value of storagePlanId
     */
    public int getStoragePlanId() {
        return storagePlanId;
    }

    /**
     * Setter method for property <tt>storagePlanId</tt>.
     * @param storagePlanId
     *            value to be assigned to property storagePlanId
     */
    public void setStoragePlanId(int storagePlanId) {
        this.storagePlanId = storagePlanId;
    }

    /**
     * Getter method for property <tt>deliveryPlanId</tt>.
     * @return property value of deliveryPlanId
     */
    public int getDeliveryPlanId() {
        return deliveryPlanId;
    }

    /**
     * Setter method for property <tt>deliveryPlanId</tt>.
     * @param deliveryPlanId
     *            value to be assigned to property deliveryPlanId
     */
    public void setDeliveryPlanId(int deliveryPlanId) {
        this.deliveryPlanId = deliveryPlanId;
    }

    /**
     * Getter method for property <tt>storageTime</tt>.
     * @return property value of storageTime
     */
    public Date getStorageTime() {
        if (null == storageTime) {
            return null;
        }
        return (Date) storageTime.clone();
    }

    /**
     * Setter method for property <tt>storageTime</tt>.
     * @param storageTime
     *            value to be assigned to property storageTime
     */
    public void setStorageTime(Date storageTime) {
        if (null == storageTime) {
            this.storageTime = null;
        } else {
            this.storageTime = (Date) storageTime.clone();
        }
    }

    /**
     * Getter method for property <tt>operator</tt>.
     * @return property value of operator
     */
    public String getOperatorName() {
        if (operatorName == null) {
            operatorName = "";
        }
        return operatorName;
    }

    /**
     * Setter method for property <tt>operator</tt>.
     * @param operator
     *            value to be assigned to property operator
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * Getter method for property <tt>deliveryTime</tt>.
     * @return property value of deliveryTime
     */
    public Date getDeliveryTime() {
        if (null == deliveryTime) {
            return null;
        }
        return (Date) deliveryTime.clone();
    }

    /**
     * Setter method for property <tt>deliveryTime</tt>.
     * @param deliveryTime
     *            value to be assigned to property deliveryTime
     */
    public void setDeliveryTime(Date deliveryTime) {
        if (null == deliveryTime) {
            this.deliveryTime = null;
        } else {
            this.deliveryTime = (Date) deliveryTime.clone();
        }
    }

    /**
     * Getter method for property <tt>businessStartTime</tt>.
     * @return property value of businessStartTime
     */
    public String getBusinessStartTime() {
        if (businessStartTime == null) {
            businessStartTime = "";
        }
        return businessStartTime;
    }

    /**
     * Setter method for property <tt>businessStartTime</tt>.
     * @param businessStartTime
     *            value to be assigned to property businessStartTime
     */
    public void setBusinessStartTime(String businessStartTime) {
        this.businessStartTime = businessStartTime;
    }

    /**
     * Getter method for property <tt>businessendtime</tt>.
     * @return property value of businessendtime
     */
    public String getBusinessendtime() {
        if (businessendtime == null) {
            businessendtime = "";
        }
        return businessendtime;
    }

    /**
     * Setter method for property <tt>businessendtime</tt>.
     * @param businessendtime
     *            value to be assigned to property businessendtime
     */
    public void setBusinessendtime(String businessendtime) {
        this.businessendtime = businessendtime;
    }

    /**
     * Getter method for property <tt>transportNo</tt>.
     * @return property value of transportNo
     */
    public String getTransportNo() {
        if (transportNo == null) {
            transportNo = "";
        }
        return transportNo;
    }

    /**
     * Setter method for property <tt>transportNo</tt>.
     * @param transportNo
     *            value to be assigned to property transportNo
     */
    public void setTransportNo(String transportNo) {
        this.transportNo = transportNo;
    }

    /**
     * Getter method for property <tt>transportType</tt>.
     * @return property value of transportType
     */
    public String getTransportType() {
        if (transportType == null) {
            transportType = "";
        }
        return transportType;
    }

    /**
     * Setter method for property <tt>transportType</tt>.
     * @param transportType
     *            value to be assigned to property transportType
     */
    public void setTransportType(String transportType) {
        this.transportType = transportType;
    }

    /**
     * Getter method for property <tt>pickupSelfTime</tt>.
     * @return property value of pickupSelfTime
     */
    public String getPickupSelfTime() {
        if (pickupSelfTime == null) {
            pickupSelfTime = "";
        }
        return pickupSelfTime;
    }

    /**
     * Setter method for property <tt>pickupSelfTime</tt>.
     * @param pickupSelfTime
     *            value to be assigned to property pickupSelfTime
     */
    public void setPickupSelfTime(String pickupSelfTime) {
        this.pickupSelfTime = pickupSelfTime;
    }

    /**
     * Getter method for property <tt>orderId</tt>.
     * @return property value of orderId
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * Setter method for property <tt>orderId</tt>.
     * @param orderId
     *            value to be assigned to property orderId
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter method for property <tt>orderNo</tt>.
     * @return property value of orderNo
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Setter method for property <tt>orderNo</tt>.
     * @param orderNo
     *            value to be assigned to property orderNo
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getStorageStartTime() {
        return storageStartTime;
    }

    public void setStorageStartTime(String storageStartTime) {
        this.storageStartTime = storageStartTime;
    }

    public String getStorageEndTime() {
        return storageEndTime;
    }

    public void setStorageEndTime(String storageEndTime) {
        this.storageEndTime = storageEndTime;
    }

    public String getDeliveryStartTime() {
        return deliveryStartTime;
    }

    public void setDeliveryStartTime(String deliveryStartTime) {
        this.deliveryStartTime = deliveryStartTime;
    }

    public String getDeliveryEndTime() {
        return deliveryEndTime;
    }

    public void setDeliveryEndTime(String deliveryEndTime) {
        this.deliveryEndTime = deliveryEndTime;
    }

    public String getReceivedStartTime() {
        return receivedStartTime;
    }

    public void setReceivedStartTime(String receivedStartTime) {
        this.receivedStartTime = receivedStartTime;
    }

    public String getReceivedEndTime() {
        return receivedEndTime;
    }

    public void setReceivedEndTime(String receivedEndTime) {
        this.receivedEndTime = receivedEndTime;
    }

    public String getReceivedTime() {
        return receivedTime;
    }

    public void setReceivedTime(String receivedTime) {
        this.receivedTime = receivedTime;
    }

    /**
     * Getter method for property <tt>deliveryId</tt>.
     * @return property value of deliveryId
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * Setter method for property <tt>deliveryId</tt>.
     * @param deliveryId
     *            value to be assigned to property deliveryId
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * Getter method for property <tt>storageVehicleId</tt>.
     * @return property value of storageVehicleId
     */
    public Integer getStorageVehicleId() {
        return storageVehicleId;
    }

    /**
     * Setter method for property <tt>storageVehicleId</tt>.
     * @param storageVehicleId
     *            value to be assigned to property storageVehicleId
     */
    public void setStorageVehicleId(Integer storageVehicleId) {
        this.storageVehicleId = storageVehicleId;
    }

    /**
     * Getter method for property <tt>vehicleStatusSearch</tt>.
     * @return property value of vehicleStatusSearch
     */
    public String getVehicleStatusSearch() {
        return vehicleStatusSearch;
    }

    /**
     * Setter method for property <tt>vehicleStatusSearch</tt>.
     * @param vehicleStatusSearch
     *            value to be assigned to property vehicleStatusSearch
     */
    public void setVehicleStatusSearch(String vehicleStatusSearch) {
        this.vehicleStatusSearch = vehicleStatusSearch;
    }

    /**
     * Getter method for property <tt>qualityStatusSearch</tt>.
     * @return property value of qualityStatusSearch
     */
    public String getQualityStatusSearch() {
        return qualityStatusSearch;
    }

    /**
     * Setter method for property <tt>qualityStatusSearch</tt>.
     * @param qualityStatusSearch
     *            value to be assigned to property qualityStatusSearch
     */
    public void setQualityStatusSearch(String qualityStatusSearch) {
        this.qualityStatusSearch = qualityStatusSearch;
    }

    /**
     * Getter method for property <tt>lockStatusSearch</tt>.
     * @return property value of lockStatusSearch
     */
    public String getLockStatusSearch() {
        return lockStatusSearch;
    }

    /**
     * Setter method for property <tt>lockStatusSearch</tt>.
     * @param lockStatusSearch
     *            value to be assigned to property lockStatusSearch
     */
    public void setLockStatusSearch(String lockStatusSearch) {
        this.lockStatusSearch = lockStatusSearch;
    }

    /**
     * Getter method for property <tt>customerId</tt>.
     * @return property value of customerId
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * Setter method for property <tt>customerId</tt>.
     * @param customerId
     *            value to be assigned to property customerId
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter method for property <tt>idList</tt>.
     * @return property value of idList
     */
    public List<Integer> getIdList() {
        return idList;
    }

    /**
     * Setter method for property <tt>idList</tt>.
     * @param idList
     *            value to be assigned to property idList
     */
    public void setIdList(List<Integer> idList) {
        this.idList = idList;
    }
}
